import type { IntakeSection } from './types';

export const ACCOUNTING_SECTIONS: IntakeSection[] = [
  {
    id: 'practice-overview',
    title: 'Practice Overview',
    description: "Let's start with your firm, team structure, and the clients you serve.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Patricia Walsh, Managing Partner',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourfirm.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'firmName',
        label: 'Firm or practice name',
        type: 'text',
        placeholder: 'e.g. Walsh & Associates CPA',
      },
      {
        id: 'firmType',
        label: 'What best describes your practice?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'cpa-firm', label: 'CPA firm' },
          { value: 'bookkeeping', label: 'Bookkeeping service' },
          { value: 'tax-prep', label: 'Tax preparation specialist' },
          { value: 'fractional-cfo', label: 'Fractional CFO / controller' },
          { value: 'payroll', label: 'Payroll services' },
          { value: 'enrolled-agent', label: 'Enrolled agent practice' },
          { value: 'virtual', label: 'Virtual / cloud-based firm' },
        ],
      },
      {
        id: 'teamSize',
        label: 'How many people are on your team?',
        type: 'radio',
        options: [
          { value: 'solo', label: 'Solo practitioner' },
          { value: '2-5', label: '2 – 5 people' },
          { value: '6-20', label: '6 – 20 people' },
          { value: '20-plus', label: '20+ people' },
        ],
      },
      {
        id: 'clientCount',
        label: 'Approximately how many active clients do you serve?',
        type: 'radio',
        options: [
          { value: 'under-25', label: 'Under 25' },
          { value: '25-100', label: '25 – 100' },
          { value: '100-500', label: '100 – 500' },
          { value: '500-plus', label: '500+' },
        ],
      },
    ],
  },
  {
    id: 'services-specializations',
    title: 'Services & Specializations',
    description: 'The services you offer and industries you specialize in shape your positioning and client tools.',
    fields: [
      {
        id: 'servicesOffered',
        label: 'Which services do you offer?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'tax-prep', label: 'Tax preparation & filing' },
          { value: 'tax-planning', label: 'Tax planning & strategy' },
          { value: 'bookkeeping', label: 'Monthly bookkeeping' },
          { value: 'payroll', label: 'Payroll processing' },
          { value: 'audit', label: 'Audit & assurance' },
          { value: 'cfo-advisory', label: 'CFO / advisory services' },
          { value: 'estate-trust', label: 'Estate & trust planning' },
          { value: 'business-formation', label: 'Business formation & entity setup' },
        ],
      },
      {
        id: 'clientIndustries',
        label: 'Which client industries do you specialize in?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'small-business', label: 'Small business (general)' },
          { value: 'real-estate', label: 'Real estate investors / landlords' },
          { value: 'healthcare', label: 'Healthcare / medical practices' },
          { value: 'nonprofit', label: 'Nonprofits' },
          { value: 'construction', label: 'Construction / contractors' },
          { value: 'restaurants', label: 'Restaurants / hospitality' },
          { value: 'individuals', label: 'Individual / personal tax' },
          { value: 'general', label: 'Industry-agnostic' },
        ],
      },
      {
        id: 'nichePositioning',
        label: 'How clearly is your niche communicated on your website?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'very-clear', label: 'Very clear — visitors know who we serve' },
          { value: 'somewhat', label: 'Somewhat — could be sharper' },
          { value: 'unclear', label: 'Unclear — we try to serve everyone' },
          { value: 'no-website', label: 'No website to evaluate' },
        ],
      },
      {
        id: 'pricingModel',
        label: 'How do you price your services?',
        type: 'radio',
        options: [
          { value: 'fixed-fee', label: 'Fixed fee per service' },
          { value: 'monthly-retainer', label: 'Monthly retainer' },
          { value: 'hourly', label: 'Hourly billing' },
          { value: 'value-based', label: 'Value-based pricing' },
          { value: 'mix', label: 'Mix of models' },
        ],
      },
    ],
  },
  {
    id: 'lead-gen-intake',
    title: 'Lead Generation & Client Intake',
    description: 'How prospects find you and what happens from first contact to signed engagement letter.',
    fields: [
      {
        id: 'leadSources',
        label: 'Where do most new clients come from?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'referrals', label: 'Client referrals' },
          { value: 'google', label: 'Google search / local SEO' },
          { value: 'cpa-directory', label: 'CPA directories (AICPA, state society)' },
          { value: 'networking', label: 'Networking / professional associations' },
          { value: 'cross-sell', label: 'Cross-sell from existing clients' },
          { value: 'paid-ads', label: 'Paid ads' },
        ],
      },
      {
        id: 'inquiryProcess',
        label: 'How do prospective clients currently reach you?',
        type: 'radio',
        options: [
          { value: 'online-form', label: 'Online contact or intake form' },
          { value: 'phone-email', label: 'Phone or email only' },
          { value: 'consultation-booking', label: 'Online consultation booking' },
          { value: 'referral-only', label: 'Referral introductions only' },
        ],
      },
      {
        id: 'clientIntake',
        label: 'How do you collect information from new clients?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. paper organizer, email questionnaire, client portal, in-person meeting...',
      },
      {
        id: 'engagementLetters',
        label: 'How are engagement letters and contracts handled?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'digital-automated', label: 'Fully digital — e-signature and automated' },
          { value: 'digital-manual', label: 'Digital — but requires manual steps' },
          { value: 'paper', label: 'Paper / in-person signing' },
          { value: 'informal', label: 'No formal engagement letter process' },
        ],
      },
      {
        id: 'leadPain',
        label: 'Where do you lose the most prospects in the intake process?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. slow response time, no online intake, prospects choose a competitor, onboarding is too manual...',
      },
    ],
  },
  {
    id: 'digital-trust',
    title: 'Digital Presence & Trust Signals',
    description: 'In financial services, trust is everything — your website is your first credibility test.',
    fields: [
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — professional, builds trust, drives inquiries' },
          { value: 'adequate', label: 'Adequate — functional but dated' },
          { value: 'outdated', label: 'Outdated — needs a full rebuild' },
          { value: 'none', label: 'No website currently' },
        ],
      },
      {
        id: 'websitePain',
        label: 'What frustrates you most about your current website?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. does not convey expertise, no client portal link, looks like every other CPA site, not mobile-friendly...',
      },
      {
        id: 'trustSignals',
        label: 'Which trust signals do you currently display?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'credentials', label: 'CPA / EA / CFP credentials' },
          { value: 'testimonials', label: 'Client testimonials' },
          { value: 'case-studies', label: 'Case studies or client results' },
          { value: 'awards', label: 'Awards or industry recognition' },
          { value: 'team-bios', label: 'Detailed team bios with photos' },
          { value: 'blog', label: 'Educational blog or resources' },
          { value: 'none', label: 'Few or no trust signals' },
        ],
      },
      {
        id: 'googleProfile',
        label: 'Is your Google Business Profile actively managed?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — photos, hours, and reviews are current' },
          { value: 'partial', label: 'Set up but not regularly maintained' },
          { value: 'no', label: 'No — not actively managed' },
        ],
      },
    ],
  },
  {
    id: 'client-communication',
    title: 'Client Communication & Technology',
    description: 'How you communicate with clients between tax season and year-round engagements.',
    fields: [
      {
        id: 'clientPortal',
        label: 'Do clients have a secure portal to upload documents, view returns, or communicate?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-robust', label: 'Yes — robust client portal (TaxDome, Karbon, etc.)' },
          { value: 'yes-basic', label: 'Yes — basic file sharing (Dropbox, ShareFile)' },
          { value: 'no-want', label: 'No — and we want to add this' },
          { value: 'no', label: 'No client portal — email only' },
        ],
      },
      {
        id: 'practiceManagement',
        label: 'What practice management or workflow tool do you use?',
        type: 'radio',
        options: [
          { value: 'taxdome', label: 'TaxDome' },
          { value: 'karbon', label: 'Karbon' },
          { value: 'canopy', label: 'Canopy' },
          { value: 'jetpack', label: 'Jetpack Workflow' },
          { value: 'quickbooks', label: 'QuickBooks Online Accountant' },
          { value: 'spreadsheets', label: 'Spreadsheets / manual tracking' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        id: 'documentCollection',
        label: 'How do you collect documents from clients during tax season?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. client portal upload, email attachments, paper drop-off, secure file share...',
      },
      {
        id: 'clientCommunication',
        label: 'How do you communicate with clients between engagements?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'email-newsletter', label: 'Email newsletter / tax tips' },
          { value: 'annual-review', label: 'Annual tax planning review calls' },
          { value: 'portal-messages', label: 'Portal messaging' },
          { value: 'social-media', label: 'Social media updates' },
          { value: 'none', label: 'Minimal communication between engagements' },
        ],
      },
    ],
  },
  {
    id: 'compliance-security',
    title: 'Compliance & Data Security',
    description: 'Financial firms have heightened obligations around data security and regulatory compliance.',
    fields: [
      {
        id: 'dataSecurity',
        label: 'What data security measures do you have in place for client information?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'encrypted-portal', label: 'Encrypted client portal' },
          { value: 'two-factor', label: 'Two-factor authentication' },
          { value: 'secure-file-transfer', label: 'Secure file transfer (not email)' },
          { value: 'cyber-insurance', label: 'Cyber liability insurance' },
          { value: 'wisp', label: 'Written Information Security Plan (WISP)' },
          { value: 'basic', label: 'Basic — password protection only' },
        ],
      },
      {
        id: 'complianceConcerns',
        label: 'Which compliance considerations are most important for your website?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'state-licensing', label: 'State licensing disclosures' },
          { value: 'ptin', label: 'PTIN / preparer identification' },
          { value: 'privacy-policy', label: 'Privacy policy / data handling' },
          { value: 'accessibility', label: 'ADA / web accessibility' },
          { value: 'not-sure', label: 'Not sure — need guidance' },
        ],
      },
      {
        id: 'securityPain',
        label: 'What is your biggest concern around client data security?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. clients emailing sensitive documents, no secure portal, phishing risk, no WISP in place...',
      },
    ],
  },
  {
    id: 'timeline-budget',
    title: 'Timeline, Budget & Final Thoughts',
    description: "Last section — let's align on priorities and investment level.",
    fields: [
      {
        id: 'primaryGoal',
        label: 'What is your primary goal for this engagement?',
        type: 'radio',
        options: [
          { value: 'new-website', label: 'Build or rebuild a professional, trustworthy website' },
          { value: 'more-clients', label: 'Generate more qualified client inquiries' },
          { value: 'client-portal', label: 'Add or improve a secure client portal' },
          { value: 'streamline-intake', label: 'Streamline client intake and onboarding' },
          { value: 'seo-local', label: 'Improve local search visibility' },
          { value: 'multiple', label: "Multiple goals — let's discuss" },
        ],
      },
      {
        id: 'launchDate',
        label: 'Is there a deadline driving this project?',
        type: 'text',
        placeholder: 'e.g. before tax season, before firm anniversary, ASAP...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will handle it ourselves' },
          { value: 'retainer', label: 'Monthly support retainer' },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'brandIdentity',
        label: 'Do you have an established brand identity (logo, colors, fonts)?',
        type: 'radio',
        options: [
          { value: 'established', label: "Yes — brand is solid, don't change it" },
          { value: 'refresh', label: 'Yes — but open to a refresh' },
          { value: 'need-help', label: 'No — we need full branding help' },
        ],
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — goals, frustrations, or questions for our team?',
        type: 'textarea',
        placeholder: 'No detail is too small.',
      },
    ],
  },
];
