import type { IntakeSection } from './types';

export const BEAUTY_WELLNESS_SECTIONS: IntakeSection[] = [
  {
    id: 'business-venue',
    title: 'Business & Venue',
    description: "Let's start with your business, location, and the experience you offer clients.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Sofia Reyes, Salon Owner',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yoursalon.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'businessName',
        label: 'Business name',
        type: 'text',
        placeholder: 'e.g. Bloom Studio Spa & Salon',
      },
      {
        id: 'businessType',
        label: 'What best describes your business?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'hair-salon', label: 'Hair salon / barbershop' },
          { value: 'nail-salon', label: 'Nail salon' },
          { value: 'spa', label: 'Day spa / med spa' },
          { value: 'massage', label: 'Massage therapy' },
          { value: 'esthetician', label: 'Esthetician / skincare' },
          { value: 'fitness', label: 'Fitness studio / personal training' },
          { value: 'yoga-pilates', label: 'Yoga / Pilates studio' },
          { value: 'wellness-center', label: 'Holistic wellness center' },
        ],
      },
      {
        id: 'locationCount',
        label: 'How many locations do you operate?',
        type: 'radio',
        options: [
          { value: 'one', label: '1 location' },
          { value: 'two-five', label: '2 – 5 locations' },
          { value: 'six-plus', label: '6+ locations / franchise' },
        ],
      },
      {
        id: 'staffCount',
        label: 'How many service providers or practitioners do you have?',
        type: 'radio',
        options: [
          { value: 'solo', label: 'Solo practitioner' },
          { value: '2-5', label: '2 – 5 providers' },
          { value: '6-15', label: '6 – 15 providers' },
          { value: '15-plus', label: '15+ providers' },
        ],
      },
    ],
  },
  {
    id: 'services-booking',
    title: 'Service Menu & Booking',
    description: 'How clients discover your services and book appointments is the core of your digital experience.',
    fields: [
      {
        id: 'bookingSystem',
        label: 'What booking system do you currently use?',
        type: 'radio',
        options: [
          { value: 'vagaro', label: 'Vagaro' },
          { value: 'booksy', label: 'Booksy' },
          { value: 'fresha', label: 'Fresha' },
          { value: 'square', label: 'Square Appointments' },
          { value: 'mindbody', label: 'Mindbody' },
          { value: 'boulevard', label: 'Boulevard' },
          { value: 'phone-walkin', label: 'Phone / walk-in only' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        id: 'onlineBooking',
        label: 'Can clients book appointments online 24/7?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-website', label: 'Yes — directly on our website' },
          { value: 'yes-third-party', label: 'Yes — through a third-party platform only' },
          { value: 'no-want', label: 'No — and we want to add this' },
          { value: 'no', label: 'No online booking' },
        ],
      },
      {
        id: 'serviceMenuOnline',
        label: 'Is your full service menu with pricing visible online?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-full', label: 'Yes — full menu with prices' },
          { value: 'yes-partial', label: 'Partial — some services listed' },
          { value: 'no-want', label: 'No — and we want to add this' },
          { value: 'no', label: 'No menu online' },
        ],
      },
      {
        id: 'bookingPain',
        label: 'What is the biggest friction in your booking or scheduling process?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. double bookings, no-shows, phone tag, clients cannot see provider availability...',
      },
      {
        id: 'waitlist',
        label: 'Do you use a waitlist or last-minute cancellation fill system?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — automated waitlist' },
          { value: 'manual', label: 'Manual — staff calls the waitlist' },
          { value: 'no-want', label: 'No — but we want this' },
          { value: 'no', label: 'No waitlist system' },
        ],
      },
    ],
  },
  {
    id: 'digital-presence',
    title: 'Digital Presence & Reviews',
    description: 'In beauty and wellness, your online reputation often decides who walks through the door.',
    fields: [
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — professional, drives bookings' },
          { value: 'adequate', label: 'Adequate — functional but not impressive' },
          { value: 'outdated', label: 'Outdated — needs a full rebuild' },
          { value: 'none', label: 'No website — booking platform only' },
        ],
      },
      {
        id: 'websitePain',
        label: 'What frustrates you most about your current online presence?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. no portfolio/gallery, booking link buried, looks dated, not mobile-friendly...',
      },
      {
        id: 'reviewPlatforms',
        label: 'Which review platforms matter most for your business?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'google', label: 'Google Reviews' },
          { value: 'yelp', label: 'Yelp' },
          { value: 'facebook', label: 'Facebook' },
          { value: 'vagaro-booksy', label: 'Vagaro / Booksy / platform reviews' },
          { value: 'instagram', label: 'Instagram (social proof)' },
        ],
      },
      {
        id: 'reviewStrategy',
        label: 'Do you have a system to ask clients for reviews after their visit?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-automated', label: 'Yes — automated text or email follow-up' },
          { value: 'yes-manual', label: 'Yes — staff ask in person' },
          { value: 'no-want', label: 'No — but we know we should' },
          { value: 'no', label: 'No review strategy' },
        ],
      },
      {
        id: 'portfolioGallery',
        label: 'Do you have a before/after or portfolio gallery on your website?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-strong', label: 'Yes — strong gallery with recent work' },
          { value: 'yes-weak', label: 'Yes — but outdated or thin' },
          { value: 'no-want', label: 'No — but we want to showcase our work' },
          { value: 'no', label: 'No portfolio online' },
        ],
      },
    ],
  },
  {
    id: 'acquisition-retention',
    title: 'Client Acquisition & Retention',
    description: 'Getting new clients in the door and keeping them coming back.',
    fields: [
      {
        id: 'leadSources',
        label: 'Where do most new clients come from?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'referrals', label: 'Client referrals' },
          { value: 'google', label: 'Google search / local SEO' },
          { value: 'instagram', label: 'Instagram' },
          { value: 'walk-in', label: 'Walk-in / street visibility' },
          { value: 'groupon-promo', label: 'Groupon / promotional offers' },
          { value: 'influencer', label: 'Influencer / creator partnerships' },
        ],
      },
      {
        id: 'newClientOffers',
        label: 'Do you run new client promotions or first-visit discounts?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-regular', label: 'Yes — regularly promoted online' },
          { value: 'yes-occasional', label: 'Yes — but not consistently marketed' },
          { value: 'no-want', label: 'No — but interested in trying' },
          { value: 'no', label: 'No new client promotions' },
        ],
      },
      {
        id: 'loyaltyProgram',
        label: 'Do you have a loyalty or rewards program?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-digital', label: 'Yes — digital loyalty program' },
          { value: 'yes-manual', label: 'Yes — punch card or manual tracking' },
          { value: 'no-want', label: 'No — and we want to launch one' },
          { value: 'no', label: 'No loyalty program' },
        ],
      },
      {
        id: 'rebookingRate',
        label: 'How would you describe your client rebooking rate?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'strong', label: 'Strong — most clients rebook before leaving' },
          { value: 'moderate', label: 'Moderate — some rebook, many do not' },
          { value: 'weak', label: 'Weak — we lose clients after first visit' },
          { value: 'unknown', label: 'Unknown — we do not track this' },
        ],
      },
      {
        id: 'emailMarketing',
        label: 'Do you have an email or SMS marketing program?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-both', label: 'Yes — email and SMS' },
          { value: 'yes-email', label: 'Yes — email only' },
          { value: 'no-want', label: 'No — and we want to build one' },
          { value: 'no', label: 'No email or SMS marketing' },
        ],
      },
    ],
  },
  {
    id: 'retail-revenue',
    title: 'Retail & Revenue Streams',
    description: 'Product sales and additional revenue lines beyond core services.',
    fields: [
      {
        id: 'retailSales',
        label: 'Do you sell retail products (skincare, hair care, supplements, etc.)?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-significant', label: 'Yes — significant revenue line' },
          { value: 'yes-minor', label: 'Yes — minor / occasional' },
          { value: 'no-want', label: 'No — but we want to add retail' },
          { value: 'no', label: 'No retail sales' },
        ],
      },
      {
        id: 'giftCards',
        label: 'Do you sell gift cards — physical or digital?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-both', label: 'Yes — physical and digital' },
          { value: 'yes-physical', label: 'Physical only' },
          { value: 'no-want', label: 'No — but we want to add this' },
          { value: 'no', label: 'No gift cards' },
        ],
      },
      {
        id: 'memberships',
        label: 'Do you offer membership or package plans?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — actively marketed' },
          { value: 'yes-exists', label: 'Yes — exists but underpromoted' },
          { value: 'no-want', label: 'No — but interested in launching' },
          { value: 'no', label: 'No memberships or packages' },
        ],
      },
      {
        id: 'additionalRevenue',
        label: 'Are there other revenue streams you want to develop?',
        type: 'textarea',
        flag: 'upsell',
        placeholder: 'e.g. online product sales, classes/workshops, affiliate partnerships, private events...',
      },
    ],
  },
  {
    id: 'operations-software',
    title: 'Operations & Software',
    description: 'The tools and processes that keep your business running smoothly behind the scenes.',
    fields: [
      {
        id: 'posSystem',
        label: 'What POS or payment system do you use?',
        type: 'radio',
        options: [
          { value: 'square', label: 'Square' },
          { value: 'stripe', label: 'Stripe' },
          { value: 'clover', label: 'Clover' },
          { value: 'integrated-booking', label: 'Integrated with booking platform' },
          { value: 'cash-only', label: 'Cash / manual' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        id: 'staffScheduling',
        label: 'How do you manage staff scheduling and commissions?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. built into booking platform, separate tool, spreadsheets, manual...',
      },
      {
        id: 'biggestOpsPain',
        label: 'What is your single biggest operational challenge today?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. no-shows, staff turnover, inventory tracking, client communication, slow checkout...',
      },
      {
        id: 'socialPlatforms',
        label: 'Which social platforms do you actively post to?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'facebook', label: 'Facebook' },
          { value: 'pinterest', label: 'Pinterest' },
          { value: 'none', label: 'Not actively posting' },
        ],
      },
    ],
  },
  {
    id: 'timeline-budget',
    title: 'Timeline, Budget & Final Thoughts',
    description: "Last section — let's align on priorities and investment level.",
    fields: [
      {
        id: 'primaryGoal',
        label: 'What is your primary goal for this engagement?',
        type: 'radio',
        options: [
          { value: 'new-website', label: 'Build or rebuild a professional website' },
          { value: 'more-bookings', label: 'Drive more online bookings' },
          { value: 'reviews-reputation', label: 'Improve reviews and online reputation' },
          { value: 'loyalty-retention', label: 'Build loyalty and improve client retention' },
          { value: 'retail-revenue', label: 'Grow retail and additional revenue streams' },
          { value: 'multiple', label: "Multiple goals — let's discuss" },
        ],
      },
      {
        id: 'launchDate',
        label: 'Is there a deadline or season driving this project?',
        type: 'text',
        placeholder: 'e.g. before holiday season, before a new location opens, ASAP...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will handle it ourselves' },
          { value: 'retainer', label: 'Monthly support retainer' },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'brandIdentity',
        label: 'Do you have an established brand identity (logo, colors, fonts)?',
        type: 'radio',
        options: [
          { value: 'established', label: "Yes — brand is solid, don't change it" },
          { value: 'refresh', label: 'Yes — but open to a refresh' },
          { value: 'need-help', label: 'No — we need full branding help' },
        ],
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — goals, frustrations, or questions for our team?',
        type: 'textarea',
        placeholder: 'No detail is too small.',
      },
    ],
  },
];
