import type { IntakeSection } from './types';

export const CATERING_SECTIONS: IntakeSection[] = [
  {
    id: 'about',
    title: 'Your Catering Business',
    description: "Let's start with who you are, what you specialize in, and the scale of your operation.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Tanya Hill, Owner & Executive Chef',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourcatering.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'businessName',
        label: 'Business name',
        type: 'text',
        placeholder: 'e.g. Elevated Fare Catering Co.',
      },
      {
        id: 'cateringType',
        label: 'What type of catering do you primarily offer?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'corporate', label: 'Corporate events / office catering' },
          { value: 'weddings', label: 'Weddings & receptions' },
          { value: 'private-parties', label: 'Private parties & social events' },
          { value: 'nonprofit-galas', label: 'Non-profit galas & fundraisers' },
          { value: 'food-trucks', label: 'Food truck or mobile catering' },
          { value: 'drop-off', label: 'Drop-off / boxed meal catering' },
          { value: 'full-service', label: 'Full-service staffed events' },
          { value: 'buffet', label: 'Buffet / family-style service' },
          { value: 'meal-prep', label: 'Meal prep / recurring meal delivery' },
        ],
      },
      {
        id: 'serviceArea',
        label: 'What geographic area do you serve?',
        type: 'text',
        placeholder: 'e.g. Greater Chicago metro, Bay Area + Napa Valley, nationwide for destination events...',
      },
      {
        id: 'eventVolume',
        label: 'How many events do you typically cater per month?',
        type: 'radio',
        options: [
          { value: 'under-5', label: 'Under 5 events' },
          { value: '5-15', label: '5 – 15 events' },
          { value: '15-30', label: '15 – 30 events' },
          { value: '30-plus', label: '30+ events' },
        ],
      },
      {
        id: 'averageGuestCount',
        label: 'What is your typical guest count range?',
        type: 'radio',
        options: [
          { value: 'under-50', label: 'Under 50 guests' },
          { value: '50-150', label: '50 – 150 guests' },
          { value: '150-500', label: '150 – 500 guests' },
          { value: '500-plus', label: '500+ guests' },
        ],
      },
    ],
  },
  {
    id: 'lead-quoting',
    title: 'Lead Capture & Quoting Process',
    description: "How new clients find you and what happens from first contact to signed contract is your revenue funnel.",
    fields: [
      {
        id: 'leadSources',
        label: 'Where do most new clients come from?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'referrals', label: 'Referrals from past clients or venues' },
          { value: 'google-search', label: 'Google search / local SEO' },
          { value: 'wedding-knot', label: 'The Knot / WeddingWire' },
          { value: 'thumbtack', label: 'Thumbtack / GigSalad' },
          { value: 'venue-preferred', label: 'Venue preferred vendor lists' },
          { value: 'social-media', label: 'Social media (Instagram, Facebook)' },
          { value: 'event-planners', label: 'Event planner partnerships' },
          { value: 'repeat-clients', label: 'Repeat corporate or recurring clients' },
        ],
      },
      {
        id: 'inquiryProcess',
        label: 'How do prospective clients currently reach you?',
        type: 'radio',
        options: [
          { value: 'online-form', label: 'Online inquiry form on our website' },
          { value: 'phone-email', label: 'Phone or email only' },
          { value: 'third-party', label: 'Through a booking platform (The Knot, Thumbtack, etc.)' },
          { value: 'mix', label: 'Mix — website, phone, and third-party' },
        ],
      },
      {
        id: 'quotingProcess',
        label: 'How do you currently build and deliver quotes or proposals?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. custom PDF, HoneyBook, Word doc, verbal quote on the phone — how long does it take?',
      },
      {
        id: 'quoteTurnaround',
        label: 'How quickly can you typically get a quote to a prospective client?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'same-day', label: 'Same day' },
          { value: '1-2-days', label: '1 – 2 business days' },
          { value: '3-5-days', label: '3 – 5 days' },
          { value: 'week-plus', label: 'More than a week' },
        ],
      },
      {
        id: 'contractSigning',
        label: 'How are contracts and deposits currently handled?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'digital-automated', label: 'Fully digital — e-signature and online payment' },
          { value: 'digital-manual', label: 'Digital — but requires back and forth' },
          { value: 'paper', label: 'Paper contracts / checks' },
          { value: 'informal', label: 'No formal contract process' },
        ],
      },
      {
        id: 'leadConversionPain',
        label: 'Where do you lose the most leads in the sales process?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. slow quote turnaround, no follow-up system, pricing questions, they ghost after the proposal...',
      },
    ],
  },
  {
    id: 'menu-dietary',
    title: 'Menu, Pricing & Dietary Options',
    description: "How you present your menu and accommodate guest needs can make or break a booking.",
    fields: [
      {
        id: 'menuStructure',
        label: 'How is your menu structured?',
        type: 'radio',
        options: [
          { value: 'packages', label: 'Set packages (e.g. Bronze / Silver / Gold)' },
          { value: 'per-person-ala-carte', label: 'Per-person pricing with add-ons' },
          { value: 'fully-custom', label: 'Fully custom quote for every event' },
          { value: 'mix', label: 'Mix of packages and custom' },
        ],
      },
      {
        id: 'menuOnline',
        label: 'Can prospective clients view your menu or packages online before contacting you?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-full', label: 'Yes — full menu or packages visible on website' },
          { value: 'yes-partial', label: 'Partial — some options are shown' },
          { value: 'no', label: 'No — clients must contact us first' },
        ],
      },
      {
        id: 'dietaryAccommodations',
        label: 'Which dietary needs do you regularly accommodate?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'vegan', label: 'Vegan' },
          { value: 'vegetarian', label: 'Vegetarian' },
          { value: 'gluten-free', label: 'Gluten-free' },
          { value: 'halal', label: 'Halal' },
          { value: 'kosher', label: 'Kosher' },
          { value: 'nut-free', label: 'Nut-free / allergy-aware' },
          { value: 'dairy-free', label: 'Dairy-free' },
          { value: 'all', label: 'All of the above' },
        ],
      },
      {
        id: 'tastings',
        label: 'Do you offer tastings for prospective clients?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-free', label: 'Yes — included for qualified prospects' },
          { value: 'yes-paid', label: 'Yes — for a fee' },
          { value: 'no-want', label: 'No — but we\'ve considered offering this' },
          { value: 'no', label: 'No tastings offered' },
        ],
      },
      {
        id: 'foodPhotography',
        label: 'What is the current state of your food and event photography?',
        type: 'radio',
        options: [
          { value: 'professional', label: 'Professional photos from real events' },
          { value: 'diy-decent', label: 'DIY / phone photos — presentable' },
          { value: 'needs-work', label: 'Needs significant improvement' },
          { value: 'none', label: 'Very few or no photos' },
        ],
      },
    ],
  },
  {
    id: 'digital-presence',
    title: 'Website & Online Presence',
    description: "Your website is your most visible salesperson — working 24/7 before any conversation begins.",
    fields: [
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — professional, up to date, drives inquiries' },
          { value: 'adequate', label: 'Adequate — functional but not impressive' },
          { value: 'outdated', label: 'Outdated — needs a full rebuild' },
          { value: 'none', label: 'No website currently' },
        ],
      },
      {
        id: 'websitePain',
        label: 'What frustrates you most about your current website or online presence?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. hard to update menu, no testimonials, bad on phones, no inquiry form...',
      },
      {
        id: 'googleProfile',
        label: 'Is your Google Business Profile active and updated?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — actively managed with photos and reviews' },
          { value: 'partial', label: 'Partially set up — some info missing' },
          { value: 'no', label: 'No — not managed' },
        ],
      },
      {
        id: 'socialPresence',
        label: 'Which social platforms do you actively post to?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'facebook', label: 'Facebook' },
          { value: 'pinterest', label: 'Pinterest' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'linkedin', label: 'LinkedIn (for corporate catering)' },
          { value: 'none', label: 'Not actively posting' },
        ],
      },
      {
        id: 'testimonials',
        label: 'Do you actively collect and display client testimonials or reviews?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-on-site', label: 'Yes — featured prominently on our website' },
          { value: 'yes-google', label: 'Yes — Google or third-party reviews only' },
          { value: 'no-want', label: 'No — but I know we should' },
          { value: 'no', label: 'No testimonials or reviews collected' },
        ],
      },
    ],
  },
  {
    id: 'event-execution',
    title: 'Staffing, Rentals & Day-of Execution',
    description: "Operational clarity here directly impacts how you price, staff, and deliver events.",
    fields: [
      {
        id: 'staffModel',
        label: 'How do you staff your events?',
        type: 'radio',
        options: [
          { value: 'in-house', label: 'Primarily in-house employees' },
          { value: 'contract-staff', label: 'Primarily contract / event staff' },
          { value: 'mix', label: 'Mix of employees and contractors' },
          { value: 'solo', label: 'Solo operator with occasional help' },
        ],
      },
      {
        id: 'rentalPartners',
        label: 'Do you partner with rental companies for linen, tableware, furniture, or tents?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-preferred', label: 'Yes — we have preferred vendor relationships' },
          { value: 'yes-client-arranges', label: 'Client arranges rentals separately' },
          { value: 'own-inventory', label: 'We own our own rental inventory' },
          { value: 'no', label: 'Rentals not part of our service' },
        ],
      },
      {
        id: 'eventManagementTool',
        label: 'What tools do you use to manage event logistics and day-of coordination?',
        type: 'text',
        flag: 'pain',
        placeholder: 'e.g. HoneyBook, Planning Pod, spreadsheets, paper run-of-show, nothing formal...',
      },
      {
        id: 'biggestOpsPain',
        label: 'What is your biggest operational challenge in executing events?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. last-minute guest count changes, staffing no-shows, communication with venue, dietary tracking...',
      },
    ],
  },
  {
    id: 'partnerships-marketing',
    title: 'Partnerships & Marketing',
    description: "Strategic partnerships and consistent marketing compound over time in the catering industry.",
    fields: [
      {
        id: 'venueRelationships',
        label: 'Do you have preferred vendor or exclusive relationships with any venues?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-exclusive', label: 'Yes — we are the exclusive caterer at one or more venues' },
          { value: 'yes-preferred', label: 'Yes — we are on preferred vendor lists' },
          { value: 'no-want', label: 'No — and we want to develop these' },
          { value: 'no', label: 'No venue partnerships' },
        ],
      },
      {
        id: 'emailMarketing',
        label: 'Do you have an email or newsletter marketing program?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-regular', label: 'Yes — regular email marketing' },
          { value: 'yes-irregular', label: 'Yes — but inconsistently' },
          { value: 'no-want', label: 'No — and I want to build one' },
          { value: 'no', label: 'No email marketing' },
        ],
      },
      {
        id: 'caseStudiesPortfolio',
        label: 'Do you have a portfolio or photo gallery of past events on your website?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-strong', label: 'Yes — strong gallery with recent events' },
          { value: 'yes-weak', label: 'Yes — but outdated or thin' },
          { value: 'no', label: 'No event gallery online' },
        ],
      },
      {
        id: 'contentCreation',
        label: 'Do you create content (reels, blog posts, behind-the-scenes) from your events?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-consistently', label: 'Yes — consistently' },
          { value: 'yes-occasionally', label: 'Occasionally — not systematic' },
          { value: 'no-want', label: 'No — but I want to start' },
          { value: 'no', label: 'No content creation from events' },
        ],
      },
    ],
  },
  {
    id: 'timeline-budget',
    title: 'Timeline, Budget & Final Thoughts',
    description: "Last section — let's align on priorities and investment level.",
    fields: [
      {
        id: 'primaryGoal',
        label: 'What is your primary goal for this engagement?',
        type: 'radio',
        options: [
          { value: 'new-website', label: 'Build or rebuild a professional website' },
          { value: 'more-inquiries', label: 'Generate more qualified event inquiries' },
          { value: 'streamline-quoting', label: 'Streamline quoting, proposals, and contracts' },
          { value: 'corporate-clients', label: 'Win more corporate or recurring clients' },
          { value: 'venue-partnerships', label: 'Get on more venue preferred vendor lists' },
          { value: 'multiple', label: "Multiple goals — let's discuss" },
        ],
      },
      {
        id: 'launchDate',
        label: 'Is there a busy season, event, or deadline driving this project?',
        type: 'text',
        placeholder: 'e.g. before wedding season, before Q4 corporate rush, ASAP...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will handle it ourselves' },
          { value: 'retainer', label: 'Monthly support retainer' },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'brandIdentity',
        label: 'Do you have an established brand identity (logo, colors, fonts)?',
        type: 'radio',
        options: [
          { value: 'established', label: "Yes — brand is strong, don't change it" },
          { value: 'refresh', label: 'Yes — but open to a visual refresh' },
          { value: 'need-help', label: 'No — we need full branding help' },
        ],
      },
      {
        id: 'competitorReference',
        label: 'Is there a catering company or event brand whose online presence you admire?',
        type: 'text',
        placeholder: 'Paste a URL or describe what you like about their positioning',
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — goals, concerns, or questions for our team?',
        type: 'textarea',
        placeholder: 'No detail is too small.',
      },
    ],
  },
];
