import type { IntakeSection } from './types';

export const CONSULTING_SECTIONS: IntakeSection[] = [
  {
    id: 'about-practice',
    title: 'About You & Your Practice',
    description: "Let's start with who you are, what you do, and how your practice is structured.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. James Okonkwo, Executive Coach & Consultant',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourpractice.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'practiceName',
        label: 'Practice or business name',
        type: 'text',
        placeholder: 'e.g. Okonkwo Leadership Group',
      },
      {
        id: 'practiceType',
        label: 'What best describes your practice?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'executive-coach', label: 'Executive / leadership coaching' },
          { value: 'business-consultant', label: 'Business / management consulting' },
          { value: 'life-coach', label: 'Life / personal development coaching' },
          { value: 'career-coach', label: 'Career coaching' },
          { value: 'fractional', label: 'Fractional executive (CFO, CMO, etc.)' },
          { value: 'trainer', label: 'Corporate trainer / facilitator' },
          { value: 'speaker', label: 'Keynote speaker / thought leader' },
        ],
      },
      {
        id: 'yearsInPractice',
        label: 'How long have you been in practice?',
        type: 'radio',
        options: [
          { value: 'under-2', label: 'Under 2 years' },
          { value: '2-5', label: '2 – 5 years' },
          { value: '6-15', label: '6 – 15 years' },
          { value: '15-plus', label: '15+ years' },
        ],
      },
      {
        id: 'teamStructure',
        label: 'How is your practice structured?',
        type: 'radio',
        options: [
          { value: 'solo', label: 'Solo practitioner' },
          { value: 'small-team', label: 'Small team (2 – 5 people)' },
          { value: 'firm', label: 'Established firm (6+ people)' },
        ],
      },
    ],
  },
  {
    id: 'ideal-client',
    title: 'Ideal Client & Niche',
    description: 'Clarity on who you serve best drives every recommendation we make.',
    fields: [
      {
        id: 'idealClient',
        label: 'Who is your ideal client?',
        type: 'textarea',
        placeholder: 'e.g. mid-market CEOs preparing for exit, first-time managers at tech startups, women re-entering the workforce...',
      },
      {
        id: 'clientIndustries',
        label: 'Which industries or sectors do you primarily serve?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'tech', label: 'Technology / SaaS' },
          { value: 'healthcare', label: 'Healthcare' },
          { value: 'finance', label: 'Finance / professional services' },
          { value: 'nonprofit', label: 'Nonprofit / social impact' },
          { value: 'manufacturing', label: 'Manufacturing / industrial' },
          { value: 'retail', label: 'Retail / consumer' },
          { value: 'general', label: 'Industry-agnostic' },
        ],
      },
      {
        id: 'clientSize',
        label: 'What size organizations do you typically work with?',
        type: 'radio',
        options: [
          { value: 'individuals', label: 'Individuals only' },
          { value: 'small-biz', label: 'Small businesses (under 50 employees)' },
          { value: 'mid-market', label: 'Mid-market (50 – 500 employees)' },
          { value: 'enterprise', label: 'Enterprise (500+ employees)' },
          { value: 'mix', label: 'Mix of all sizes' },
        ],
      },
      {
        id: 'nichePositioning',
        label: 'How clearly is your niche communicated on your current website or materials?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'very-clear', label: 'Very clear — visitors know immediately who I help' },
          { value: 'somewhat', label: 'Somewhat — could be sharper' },
          { value: 'unclear', label: 'Unclear — I try to serve everyone' },
          { value: 'no-website', label: 'No website to evaluate' },
        ],
      },
    ],
  },
  {
    id: 'service-delivery',
    title: 'Service Delivery & Packaging',
    description: 'How you package and deliver your expertise affects pricing power and scalability.',
    fields: [
      {
        id: 'serviceFormats',
        label: 'How do you deliver your services?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: '1-on-1', label: '1-on-1 coaching / consulting sessions' },
          { value: 'group', label: 'Group programs / cohorts' },
          { value: 'workshops', label: 'Workshops / training sessions' },
          { value: 'retainer', label: 'Monthly retainer engagements' },
          { value: 'project', label: 'Fixed-scope project work' },
          { value: 'digital-products', label: 'Digital products (courses, templates, guides)' },
          { value: 'speaking', label: 'Speaking engagements' },
        ],
      },
      {
        id: 'packagingClarity',
        label: 'Are your service offerings clearly packaged and priced on your website?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — clear packages with visible pricing' },
          { value: 'partial', label: 'Partially — some offerings described, pricing on request' },
          { value: 'no-want', label: 'No — and I want to package and price more clearly' },
          { value: 'no', label: 'No — everything is custom / discovery-call based' },
        ],
      },
      {
        id: 'bookingProcess',
        label: 'How do prospective clients currently book a discovery call or session?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'online-scheduler', label: 'Online scheduler (Calendly, Acuity, etc.)' },
          { value: 'contact-form', label: 'Contact form — then manual scheduling' },
          { value: 'phone-email', label: 'Phone or email only' },
          { value: 'no-process', label: 'No formal booking process' },
        ],
      },
      {
        id: 'deliveryPain',
        label: 'What is the biggest friction in your client delivery process?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. onboarding is manual, no client portal, session notes scattered, follow-up is inconsistent...',
      },
    ],
  },
  {
    id: 'lead-gen-marketing',
    title: 'Lead Generation & Marketing',
    description: 'How you attract and convert prospects into paying clients.',
    fields: [
      {
        id: 'leadSources',
        label: 'Where do most new clients come from?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'referrals', label: 'Referrals from past clients' },
          { value: 'linkedin', label: 'LinkedIn' },
          { value: 'google', label: 'Google search' },
          { value: 'speaking', label: 'Speaking engagements / events' },
          { value: 'content', label: 'Blog, podcast, or newsletter' },
          { value: 'networking', label: 'Networking groups / associations' },
          { value: 'paid-ads', label: 'Paid ads' },
        ],
      },
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — professional, converts visitors' },
          { value: 'adequate', label: 'Adequate — exists but underperforms' },
          { value: 'outdated', label: 'Outdated — needs a full rebuild' },
          { value: 'none', label: 'No website currently' },
        ],
      },
      {
        id: 'websitePain',
        label: 'What frustrates you most about your current online presence?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. does not convey my expertise, no clear CTA, looks generic, hard to update...',
      },
      {
        id: 'emailList',
        label: 'Do you have an email list you market to?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — active list with regular sends' },
          { value: 'yes-dormant', label: 'Yes — but rarely used' },
          { value: 'no-want', label: 'No — and I want to build one' },
          { value: 'no', label: 'No email list' },
        ],
      },
    ],
  },
  {
    id: 'client-experience',
    title: 'Client Experience & Systems',
    description: 'The systems behind a great client experience — from onboarding to offboarding.',
    fields: [
      {
        id: 'onboardingProcess',
        label: 'How do you onboard new clients?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. welcome email, intake questionnaire, kickoff call, contract signing — what is manual vs automated?',
      },
      {
        id: 'clientPortal',
        label: 'Do clients have a portal or hub to access resources, session notes, or progress?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — dedicated client portal or platform' },
          { value: 'partial', label: 'Partially — shared folders or email' },
          { value: 'no-want', label: 'No — and I want to add this' },
          { value: 'no', label: 'No client hub' },
        ],
      },
      {
        id: 'contractPayments',
        label: 'How are contracts and payments handled?',
        type: 'radio',
        options: [
          { value: 'fully-digital', label: 'Fully digital — e-signature and online payment' },
          { value: 'partial', label: 'Partially digital — some manual steps' },
          { value: 'manual', label: 'Manual — invoices and checks' },
        ],
      },
      {
        id: 'crmTool',
        label: 'What CRM or client management tool do you use?',
        type: 'text',
        placeholder: 'e.g. HubSpot, Dubsado, HoneyBook, Notion, spreadsheets, none...',
      },
    ],
  },
  {
    id: 'content-thought-leadership',
    title: 'Content & Thought Leadership',
    description: 'Content is the long game for consultants and coaches — let us see where you stand.',
    fields: [
      {
        id: 'contentFormats',
        label: 'What content do you currently create?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'blog', label: 'Blog posts / articles' },
          { value: 'newsletter', label: 'Email newsletter' },
          { value: 'podcast', label: 'Podcast' },
          { value: 'video', label: 'Video (YouTube, LinkedIn)' },
          { value: 'social', label: 'Social media posts' },
          { value: 'case-studies', label: 'Case studies / client results' },
          { value: 'none', label: 'Not creating content regularly' },
        ],
      },
      {
        id: 'contentGoal',
        label: 'What role should content play in your business growth?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'primary-lead-gen', label: 'Primary lead generation channel' },
          { value: 'credibility', label: 'Credibility and trust-building' },
          { value: 'nurture', label: 'Nurture existing prospects' },
          { value: 'not-priority', label: 'Not a current priority' },
        ],
      },
      {
        id: 'digitalProducts',
        label: 'Do you sell or want to sell digital products (courses, templates, memberships)?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — already selling digital products' },
          { value: 'yes-planning', label: 'Planning to launch soon' },
          { value: 'no-want', label: 'No — but interested in exploring this' },
          { value: 'no', label: 'No plans for digital products' },
        ],
      },
      {
        id: 'testimonials',
        label: 'Do you actively collect and display client testimonials or case studies?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-prominent', label: 'Yes — featured prominently' },
          { value: 'yes-weak', label: 'Yes — but not well presented' },
          { value: 'no-want', label: 'No — but I know I should' },
          { value: 'no', label: 'No testimonials collected' },
        ],
      },
    ],
  },
  {
    id: 'timeline-budget',
    title: 'Timeline, Budget & Final Thoughts',
    description: "Last section — let's align on priorities and investment level.",
    fields: [
      {
        id: 'primaryGoal',
        label: 'What is your primary goal for this engagement?',
        type: 'radio',
        options: [
          { value: 'new-website', label: 'Build or rebuild a professional website' },
          { value: 'more-clients', label: 'Generate more qualified client inquiries' },
          { value: 'package-offerings', label: 'Package and price my services more clearly' },
          { value: 'content-strategy', label: 'Develop a content and thought leadership strategy' },
          { value: 'client-systems', label: 'Streamline client onboarding and delivery systems' },
          { value: 'multiple', label: "Multiple goals — let's discuss" },
        ],
      },
      {
        id: 'launchDate',
        label: 'Is there a deadline driving this project?',
        type: 'text',
        placeholder: 'e.g. before a speaking engagement, before launching a new program, ASAP...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'I will handle it myself' },
          { value: 'retainer', label: 'Monthly support retainer' },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'brandIdentity',
        label: 'Do you have an established brand identity (logo, colors, fonts)?',
        type: 'radio',
        options: [
          { value: 'established', label: "Yes — brand is solid, don't change it" },
          { value: 'refresh', label: 'Yes — but open to a refresh' },
          { value: 'need-help', label: 'No — I need full branding help' },
        ],
      },
      {
        id: 'competitorReference',
        label: 'Is there a consultant or coach whose online presence you admire?',
        type: 'text',
        placeholder: 'Paste a URL or describe what draws you to their positioning',
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — goals, frustrations, or questions for our team?',
        type: 'textarea',
        placeholder: 'No detail is too small.',
      },
    ],
  },
];
