import type { IntakeSection } from './types';

export const DISCOVERY_SECTIONS: IntakeSection[] = [
  {
    id: 'intro',
    title: 'Tell us about your business.',
    description:
      'This discovery session helps us understand where you are today — and where we can take you.',
    fields: [
      {
        id: 'name',
        label: 'Your full name',
        type: 'text',
        placeholder: 'Jane Smith',
        required: true,
      },
      {
        id: 'company',
        label: 'Company / organization',
        type: 'text',
        placeholder: 'Acme Corp',
        required: true,
      },
      {
        id: 'role',
        label: 'Your role / title',
        type: 'text',
        placeholder: 'CEO, Operations Director...',
        required: true,
      },
      {
        id: 'email',
        label: 'Best email to reach you',
        type: 'email',
        placeholder: 'jane@acmecorp.com',
        required: true,
      },
    ],
  },
  {
    id: 'services',
    title: 'What are you looking to transform?',
    description: "Select all areas you'd like to explore. We'll tailor this session accordingly.",
    fields: [
      {
        id: 'services',
        label: 'Services of interest',
        type: 'checkbox',
        required: true,
        options: [
          {
            value: 'webops',
            label: 'WebOps',
            sub: 'Digital infrastructure — build and run your web presence',
          },
          {
            value: 'revops',
            label: 'RevOps',
            sub: 'Pipeline, CRM, GTM systems, and marketing execution',
          },
          {
            value: 'managed_ops',
            label: 'Managed Ops',
            sub: 'Cross-functional transformation and full operational ownership',
          },
        ],
      },
    ],
  },
  {
    id: 'business',
    title: 'Paint us a picture.',
    description: 'The more context you share, the better we can identify opportunities.',
    fields: [
      {
        id: 'industry',
        label: 'Industry',
        type: 'select',
        placeholder: 'Select your industry',
        required: true,
        options: [
          { value: 'technology-saas', label: 'Technology / SaaS' },
          { value: 'ecommerce-retail', label: 'E-Commerce / Retail' },
          { value: 'professional-services', label: 'Professional Services' },
          { value: 'healthcare', label: 'Healthcare' },
          { value: 'manufacturing', label: 'Manufacturing' },
          { value: 'real-estate', label: 'Real Estate' },
          { value: 'non-profit', label: 'Non-Profit' },
          { value: 'financial-services', label: 'Financial Services' },
          { value: 'hospitality-events', label: 'Hospitality & Events' },
          { value: 'media-entertainment', label: 'Media & Entertainment' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        id: 'team_size',
        label: 'Team size',
        type: 'select',
        placeholder: 'Select range',
        required: true,
        options: [
          { value: 'solo', label: 'Solo / Freelance' },
          { value: '2-10', label: '2–10' },
          { value: '11-50', label: '11–50' },
          { value: '51-250', label: '51–250' },
          { value: '251-1000', label: '251–1,000' },
          { value: '1000-plus', label: '1,000+' },
        ],
      },
      {
        id: 'revenue_range',
        label: 'Annual revenue (approximate)',
        type: 'select',
        required: true,
        options: [
          { value: 'prefer-not-to-say', label: 'Prefer not to say' },
          { value: 'pre-revenue', label: 'Pre-revenue' },
          { value: 'under-250k', label: 'Under $250K' },
          { value: '250k-1m', label: '$250K–$1M' },
          { value: '1m-5m', label: '$1M–$5M' },
          { value: '5m-25m', label: '$5M–$25M' },
          { value: '25m-plus', label: '$25M+' },
        ],
      },
      {
        id: 'describe',
        label: 'Describe what your business does',
        type: 'textarea',
        placeholder:
          'What do you sell or deliver, who do you serve, and what makes you different?',
        required: true,
      },
    ],
  },
  {
    id: 'pain',
    title: 'Where does the friction live?',
    description: 'Be candid — the biggest problems are where the biggest wins hide.',
    fields: [
      {
        id: 'biggest_challenge',
        label: 'What is your single biggest operational challenge right now?',
        type: 'textarea',
        placeholder:
          "e.g., Our sales team spends hours on manual data entry. Reporting takes days. We can't scale without adding headcount...",
        required: true,
        flag: 'pain',
      },
      {
        id: 'pain_areas',
        label: 'Where do you feel the most pain? (select all that apply)',
        type: 'tags',
        required: true,
        flag: 'pain',
        options: [
          { value: 'manual-processes', label: 'Manual processes' },
          { value: 'disconnected-tools', label: 'Disconnected tools' },
          { value: 'slow-reporting', label: 'Slow reporting' },
          { value: 'revenue-leakage', label: 'Revenue leakage' },
          { value: 'poor-visibility', label: 'Poor visibility' },
          { value: 'scaling-bottlenecks', label: 'Scaling bottlenecks' },
          { value: 'customer-churn', label: 'Customer churn' },
          { value: 'cash-flow', label: 'Cash flow' },
          { value: 'data-silos', label: 'Data silos' },
          { value: 'team-alignment', label: 'Team alignment' },
          { value: 'compliance-burden', label: 'Compliance burden' },
          { value: 'forecasting-accuracy', label: 'Forecasting accuracy' },
        ],
      },
      {
        id: 'tried_before',
        label: 'Have you attempted to solve this before?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes-internally', label: 'Yes — internally' },
          { value: 'yes-vendor', label: 'Yes — with an outside vendor' },
          { value: 'no', label: 'No — first time addressing this' },
          { value: 'partial', label: 'Partially addressed, still unresolved' },
        ],
      },
    ],
  },
  {
    id: 'tech',
    title: 'Your current tech landscape.',
    description: 'Understanding your stack helps us spot quick wins and integration opportunities.',
    fields: [
      {
        id: 'crm',
        label: 'CRM (if any)',
        type: 'text',
        placeholder: 'Salesforce, HubSpot, Pipedrive, none...',
      },
      {
        id: 'erp',
        label: 'ERP / financial system',
        type: 'text',
        placeholder: 'QuickBooks, NetSuite, SAP, Xero, none...',
      },
      {
        id: 'project_tools',
        label: 'Project management / ops tools',
        type: 'text',
        placeholder: 'Asana, Monday, Notion, ClickUp...',
      },
      {
        id: 'data_tools',
        label: 'Reporting / analytics tools',
        type: 'text',
        placeholder: 'Looker, Power BI, Excel, Google Sheets...',
      },
      {
        id: 'tech_satisfaction',
        label: 'How well does your current tech stack serve your business?',
        type: 'radio',
        required: true,
        options: [
          { value: 'very-well', label: 'Very well — minor tweaks needed' },
          { value: 'somewhat', label: 'Somewhat — gaps exist' },
          { value: 'poorly', label: "Poorly — we've outgrown it" },
          { value: 'no-stack', label: 'We have no real stack yet' },
        ],
      },
    ],
  },
  {
    id: 'revenue',
    title: "Let's talk numbers.",
    description:
      'Understanding your revenue model helps us quantify the impact of what we\'d build together.',
    fields: [
      {
        id: 'rev_model',
        label: 'Revenue model(s) in play',
        type: 'tags',
        required: true,
        options: [
          { value: 'subscriptions-saas', label: 'Subscriptions / SaaS' },
          { value: 'one-time-sales', label: 'One-time sales' },
          { value: 'services-retainer', label: 'Services / retainer' },
          { value: 'marketplace-commission', label: 'Marketplace / commission' },
          { value: 'product-licensing', label: 'Product licensing' },
          { value: 'grants-funding', label: 'Grants / funding' },
          { value: 'advertising', label: 'Advertising' },
          { value: 'mixed', label: 'Mixed' },
        ],
      },
      {
        id: 'rev_goal',
        label: 'What is your revenue goal for the next 12 months?',
        type: 'textarea',
        placeholder:
          'e.g., Grow from $2M to $5M ARR, reach profitability, add 3 new enterprise accounts...',
        required: true,
      },
      {
        id: 'leak_estimate',
        label: 'How much revenue do you think you\'re leaving on the table due to inefficiency?',
        type: 'radio',
        required: true,
        options: [
          { value: 'under-50k', label: 'Less than $50K / year' },
          { value: '50k-250k', label: '$50K–$250K / year' },
          { value: '250k-1m', label: '$250K–$1M / year' },
          { value: '1m-plus', label: '$1M+ / year' },
          { value: 'unknown', label: "I genuinely don't know" },
        ],
      },
      {
        id: 'urgency',
        label: 'How urgent is solving this?',
        type: 'radio',
        required: true,
        options: [
          { value: 'critical', label: 'Critical — we need help now' },
          { value: 'high', label: 'High — within 90 days' },
          { value: 'moderate', label: 'Moderate — planning for Q3–Q4' },
          { value: 'exploratory', label: 'Exploratory — just looking' },
        ],
      },
    ],
  },
  {
    id: 'vision',
    title: 'What does winning look like?',
    description:
      "Help us understand where you're trying to go and what a partnership needs to deliver.",
    fields: [
      {
        id: 'success_def',
        label: 'Define success — 12 months from now, what has changed?',
        type: 'textarea',
        placeholder:
          'e.g., Zero time on manual reporting. Revenue up 40%. Full pipeline visibility...',
        required: true,
      },
      {
        id: 'decision_maker',
        label: 'Are you the final decision-maker for this engagement?',
        type: 'radio',
        required: true,
        options: [
          { value: 'yes', label: 'Yes, this is my call' },
          { value: 'stakeholder', label: "I'm a key stakeholder — others are involved" },
          { value: 'researching', label: "I'm researching on behalf of someone else" },
        ],
      },
      {
        id: 'budget',
        label: 'Approximate budget range for this initiative?',
        type: 'radio',
        required: true,
        options: [
          { value: 'under-10k', label: 'Under $10K' },
          { value: '10k-30k', label: '$10K–$30K' },
          { value: '30k-75k', label: '$30K–$75K' },
          { value: '75k-150k', label: '$75K–$150K' },
          { value: '150k-plus', label: '$150K+' },
          { value: 'tbd', label: 'Budget TBD / pending approval' },
        ],
      },
      {
        id: 'timeline',
        label: 'Ideal timeline to begin?',
        type: 'radio',
        required: true,
        options: [
          { value: 'immediately', label: 'Immediately' },
          { value: 'within-30-days', label: 'Within 30 days' },
          { value: '1-3-months', label: '1–3 months' },
          { value: '3-6-months', label: '3–6 months' },
          { value: 'flexible', label: 'Flexible' },
        ],
      },
    ],
  },
  {
    id: 'final',
    title: 'Last thing.',
    description: "This is your space to share anything we haven't covered yet.",
    fields: [
      {
        id: 'heard',
        label: 'How did you hear about us?',
        type: 'radio',
        required: true,
        options: [
          { value: 'referral', label: 'Referral' },
          { value: 'social-media', label: 'Social media' },
          { value: 'online-search', label: 'Online search' },
          { value: 'event', label: 'Event / conference' },
          { value: 'existing-relationship', label: 'Existing relationship' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        id: 'referral_name',
        label: 'Who referred you?',
        type: 'text',
        placeholder: 'Full name of the person who sent you our way',
        required: true,
        showWhen: { fieldId: 'heard', value: 'referral' },
      },
      {
        id: 'anything_else',
        label: 'Anything you want us to know before we connect?',
        type: 'textarea',
        placeholder: 'Open floor — context, concerns, questions, expectations...',
      },
    ],
  },
];
