import type { IntakeSection } from './types';

export const ECOMMERCE_SECTIONS: IntakeSection[] = [
  {
    id: 'store-brand',
    title: 'Your Store & Brand',
    description: "Let's start with who you are and what you sell.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Alex Chen, Founder & CEO',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourstore.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'storeName',
        label: 'What is your store or brand name?',
        type: 'text',
        placeholder: 'e.g. Coastal Supply Co.',
      },
      {
        id: 'productCategory',
        label: 'What do you primarily sell?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'physical-goods', label: 'Physical / tangible goods' },
          { value: 'digital-products', label: 'Digital products / downloads' },
          { value: 'subscriptions', label: 'Subscription boxes or recurring orders' },
          { value: 'services', label: 'Services or experiences' },
          { value: 'handmade-crafts', label: 'Handmade / artisan products' },
          { value: 'b2b-wholesale', label: 'B2B / wholesale' },
        ],
      },
      {
        id: 'monthlyOrders',
        label: 'Approximately how many orders do you process per month?',
        type: 'radio',
        options: [
          { value: 'under-50', label: 'Under 50 orders' },
          { value: '50-250', label: '50 – 250 orders' },
          { value: '250-1000', label: '250 – 1,000 orders' },
          { value: '1000-plus', label: '1,000+ orders' },
        ],
      },
    ],
  },
  {
    id: 'current-platform',
    title: 'Current Platform & Technology',
    description: "Help us understand what's powering your store today and where things break down.",
    fields: [
      {
        id: 'currentPlatform',
        label: 'What platform is your store currently on?',
        type: 'radio',
        options: [
          { value: 'shopify', label: 'Shopify' },
          { value: 'woocommerce', label: 'WooCommerce (WordPress)' },
          { value: 'bigcommerce', label: 'BigCommerce' },
          { value: 'wix-squarespace', label: 'Wix / Squarespace' },
          { value: 'custom', label: 'Custom-built' },
          { value: 'no-store', label: 'No online store yet' },
        ],
      },
      {
        id: 'platformMigration',
        label: 'Are you open to migrating to a different platform?',
        type: 'radio',
        options: [
          { value: 'yes-open', label: "Yes — whatever gives us the best results" },
          { value: 'prefer-current', label: 'Prefer to stay on our current platform' },
          { value: 'undecided', label: 'Undecided — depends on cost and features' },
          { value: 'no-migrate', label: 'No — staying put' },
        ],
      },
      {
        id: 'biggestPlatformPain',
        label: 'What frustrates you most about your current setup?',
        type: 'textarea',
        sub: 'Nothing is too small — checkout friction, inventory headaches, speed issues, all fair game.',
        placeholder: 'e.g. Our checkout abandonment is high, product pages are slow to update...',
      },
      {
        id: 'analytics',
        label: 'Do you track analytics and conversion data today?',
        type: 'radio',
        options: [
          { value: 'yes-ga-pixel', label: 'Yes — Google Analytics and/or Meta Pixel' },
          { value: 'yes-platform-only', label: 'Only platform built-in analytics (Shopify, etc.)' },
          { value: 'no', label: 'No analytics set up' },
          { value: 'not-sure', label: 'Not sure' },
        ],
      },
    ],
  },
  {
    id: 'catalog-merchandising',
    title: 'Catalog & Merchandising',
    description: "Let's understand how you manage and present your products.",
    fields: [
      {
        id: 'skuCount',
        label: 'How many SKUs or products do you carry?',
        type: 'radio',
        options: [
          { value: 'under-25', label: 'Under 25' },
          { value: '25-100', label: '25 – 100' },
          { value: '100-500', label: '100 – 500' },
          { value: '500-plus', label: '500+' },
        ],
      },
      {
        id: 'catalogManagement',
        label: 'How do you currently manage product data and inventory?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. Shopify admin, spreadsheets, supplier feed, ERP...',
      },
      {
        id: 'productPhotoVideo',
        label: 'What is the current state of your product photography and media?',
        type: 'radio',
        options: [
          { value: 'professional', label: 'Professional photos and/or video' },
          { value: 'diy-decent', label: 'DIY but presentable' },
          { value: 'needs-work', label: 'Needs significant improvement' },
          { value: 'no-media', label: "We don't have much media yet" },
        ],
      },
      {
        id: 'searchFilter',
        label: 'Do customers struggle to find what they are looking for on your store?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-definitely', label: 'Yes — our search and filters are weak' },
          { value: 'somewhat', label: 'Somewhat — could be better' },
          { value: 'no', label: 'No — navigation and search work well' },
        ],
      },
    ],
  },
  {
    id: 'conversion-checkout',
    title: 'Conversion & Checkout',
    description: "This is where revenue is won or lost. Let's dig in.",
    fields: [
      {
        id: 'conversionRate',
        label: 'Do you know your current conversion rate?',
        type: 'radio',
        options: [
          { value: 'yes-happy', label: "Yes, and I'm happy with it" },
          { value: 'yes-low', label: 'Yes, and I know it needs improvement' },
          { value: 'no', label: "No, I don't track it" },
        ],
      },
      {
        id: 'abandonedCart',
        label: 'Do you have an abandoned cart recovery strategy?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — automated emails or SMS are set up' },
          { value: 'no-want', label: 'No, but I want to add this' },
          { value: 'no', label: 'No recovery strategy currently' },
        ],
      },
      {
        id: 'checkoutFriction',
        label: 'What checkout options do you currently offer?',
        type: 'checkbox',
        options: [
          { value: 'guest-checkout', label: 'Guest checkout (no account required)' },
          { value: 'shop-pay', label: 'Shop Pay / accelerated checkout' },
          { value: 'paypal', label: 'PayPal' },
          { value: 'buy-now-pay-later', label: 'Buy now pay later (Klarna, Afterpay, etc.)' },
          { value: 'crypto', label: 'Crypto / alternative payments' },
          { value: 'none', label: 'Credit card only' },
        ],
      },
      {
        id: 'upsellsCrossSells',
        label: 'Do you currently run product upsells or cross-sells?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — on product and/or cart pages' },
          { value: 'want', label: 'No, but I want to implement this' },
          { value: 'no', label: 'No plans for upsells right now' },
        ],
      },
    ],
  },
  {
    id: 'marketing-retention',
    title: 'Marketing & Customer Retention',
    description: "Acquiring customers is hard — keeping them is where the profit is.",
    fields: [
      {
        id: 'activeChannels',
        label: 'Which marketing channels are you currently active on?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'email-marketing', label: 'Email marketing (Klaviyo, Mailchimp, etc.)' },
          { value: 'sms-marketing', label: 'SMS / text marketing' },
          { value: 'meta-ads', label: 'Meta (Facebook / Instagram) ads' },
          { value: 'google-ads', label: 'Google / Shopping ads' },
          { value: 'tiktok', label: 'TikTok organic or ads' },
          { value: 'influencer', label: 'Influencer / affiliate marketing' },
          { value: 'seo-organic', label: 'SEO / organic search' },
          { value: 'none', label: 'No active marketing yet' },
        ],
      },
      {
        id: 'emailList',
        label: 'Do you have an email list? If so, how large?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'no-list', label: 'No list yet' },
          { value: 'under-500', label: 'Under 500 subscribers' },
          { value: '500-5k', label: '500 – 5,000 subscribers' },
          { value: '5k-plus', label: '5,000+ subscribers' },
        ],
      },
      {
        id: 'loyaltyProgram',
        label: 'Do you have or want a loyalty/rewards program?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — already in place' },
          { value: 'want', label: 'No, but this is something I want' },
          { value: 'no', label: 'Not a priority right now' },
        ],
      },
      {
        id: 'reviewsUgc',
        label: 'Do you actively collect product reviews or user-generated content?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — reviews are a core part of our strategy' },
          { value: 'somewhat', label: 'We have some but not systematically' },
          { value: 'no', label: 'We don\'t collect reviews currently' },
        ],
      },
    ],
  },
  {
    id: 'fulfillment-operations',
    title: 'Fulfillment & Operations',
    description: "How products move from your store to your customer's door matters to your brand.",
    fields: [
      {
        id: 'fulfillmentMethod',
        label: 'How do you currently fulfill orders?',
        type: 'radio',
        options: [
          { value: 'self-fulfill', label: 'We pack and ship ourselves' },
          { value: '3pl', label: '3PL / fulfillment center (ShipBob, etc.)' },
          { value: 'dropship', label: 'Dropshipping / print-on-demand' },
          { value: 'hybrid', label: 'Mix of self-fulfill and 3PL' },
        ],
      },
      {
        id: 'returnsProcess',
        label: 'How do you handle returns and exchanges today?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. manual email back-and-forth, no formal process, Returnly app...',
      },
      {
        id: 'inventoryTracking',
        label: 'How do you track inventory across channels?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'platform-only', label: 'Platform only (Shopify, WooCommerce, etc.)' },
          { value: 'erp-wms', label: 'ERP or warehouse management system' },
          { value: 'spreadsheets', label: 'Spreadsheets / manual tracking' },
          { value: 'no-tracking', label: "We don't really track it" },
        ],
      },
      {
        id: 'multiChannel',
        label: 'Do you sell on marketplaces in addition to your own store?',
        type: 'checkbox',
        flag: 'upsell',
        options: [
          { value: 'amazon', label: 'Amazon' },
          { value: 'etsy', label: 'Etsy' },
          { value: 'ebay', label: 'eBay' },
          { value: 'walmart', label: 'Walmart Marketplace' },
          { value: 'none', label: 'No — own store only' },
        ],
      },
    ],
  },
  {
    id: 'timeline-support',
    title: 'Timeline, Budget & Final Thoughts',
    description: 'Last section — help us understand your timeline, investment level, and anything else.',
    fields: [
      {
        id: 'launchDate',
        label: 'Is there a target date or event driving this project?',
        type: 'text',
        placeholder: 'e.g. Before Q4/holiday season, before a product launch, ASAP...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how do you want to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will manage it ourselves' },
          { value: 'retainer', label: "We'd like a monthly support retainer" },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'competitorReference',
        label: 'Is there a competitor or store you admire that we should know about?',
        type: 'text',
        placeholder: 'Paste a URL or describe what you like about it',
      },
      {
        id: 'additionalNotes',
        label: 'Anything else you want to share — goals, blockers, or questions for us?',
        type: 'textarea',
        placeholder: 'Nothing is too small or too big.',
      },
    ],
  },
];
