import type { IntakeSection } from './types';

export const GENERAL_BUSINESS_SECTIONS: IntakeSection[] = [
  {
    id: 'business-overview',
    title: 'Your Business',
    description: "Let's start with who you are, what you do, and who you serve.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Maria Lopez, Owner & CEO',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourbusiness.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'businessName',
        label: 'Business name',
        type: 'text',
        placeholder: 'e.g. Apex Services LLC',
      },
      {
        id: 'industry',
        label: 'What industry or category best describes your business?',
        type: 'text',
        placeholder: 'e.g. mobile detailing, staffing agency, tutoring, pet services, security...',
      },
      {
        id: 'businessModel',
        label: 'How do you primarily deliver value to customers?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'in-person-service', label: 'In-person service (at our location)' },
          { value: 'mobile-service', label: 'Mobile / on-site at customer locations' },
          { value: 'online-service', label: 'Online / remote services' },
          { value: 'physical-product', label: 'Physical products' },
          { value: 'digital-product', label: 'Digital products or downloads' },
          { value: 'subscription', label: 'Subscription or membership' },
          { value: 'b2b', label: 'B2B — we sell to other businesses' },
          { value: 'b2c', label: 'B2C — we sell directly to consumers' },
        ],
      },
      {
        id: 'yearsInBusiness',
        label: 'How long have you been in business?',
        type: 'radio',
        options: [
          { value: 'under-1', label: 'Less than 1 year' },
          { value: '1-3', label: '1 – 3 years' },
          { value: '3-10', label: '3 – 10 years' },
          { value: '10-plus', label: '10+ years' },
        ],
      },
    ],
  },
  {
    id: 'online-presence',
    title: 'Current Online Presence',
    description: "How you show up online determines how customers find and evaluate you.",
    fields: [
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — professional, up to date, generates leads' },
          { value: 'adequate', label: 'Functional but not impressive' },
          { value: 'outdated', label: 'Outdated — needs a full rebuild' },
          { value: 'none', label: 'No website currently' },
        ],
      },
      {
        id: 'websitePains',
        label: 'What frustrates you most about your current website or online presence?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. looks unprofessional, hard to update, no leads, not mobile-friendly, slow...',
      },
      {
        id: 'googleProfile',
        label: 'Do you have a Google Business Profile and is it actively managed?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — updated with photos and responding to reviews' },
          { value: 'yes-inactive', label: 'Yes — but not actively managed' },
          { value: 'no', label: 'No Google Business Profile' },
        ],
      },
      {
        id: 'socialMedia',
        label: 'Which social platforms are you active on?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'facebook', label: 'Facebook' },
          { value: 'linkedin', label: 'LinkedIn' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'youtube', label: 'YouTube' },
          { value: 'none', label: 'Not active on social media' },
        ],
      },
    ],
  },
  {
    id: 'lead-customer-acquisition',
    title: 'Lead Generation & Customer Acquisition',
    description: "How new customers find you and what the journey looks like before they buy.",
    fields: [
      {
        id: 'leadSources',
        label: 'Where do most new customers come from?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'referrals', label: 'Referrals / word of mouth' },
          { value: 'google-organic', label: 'Google organic / SEO' },
          { value: 'google-ads', label: 'Google Ads / PPC' },
          { value: 'social-ads', label: 'Social media ads' },
          { value: 'directory', label: 'Directory listings (Yelp, Angi, etc.)' },
          { value: 'networking', label: 'Networking / events / partnerships' },
          { value: 'repeat', label: 'Repeat customers' },
          { value: 'no-clear-source', label: 'No clear lead source tracked' },
        ],
      },
      {
        id: 'leadVolume',
        label: 'How many inbound leads or inquiries do you receive per month on average?',
        type: 'radio',
        options: [
          { value: 'under-10', label: 'Under 10' },
          { value: '10-50', label: '10 – 50' },
          { value: '50-200', label: '50 – 200' },
          { value: '200-plus', label: '200+' },
        ],
      },
      {
        id: 'leadConversion',
        label: 'How well do you convert leads into paying customers?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'strong', label: 'Strong — most leads close' },
          { value: 'average', label: 'Average — room for improvement' },
          { value: 'weak', label: 'Weak — losing too many leads' },
          { value: 'unknown', label: "I don't track this" },
        ],
      },
      {
        id: 'followUpProcess',
        label: 'What happens after someone contacts you or fills out a form?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. we call within 24 hrs, reply by email, no formal process...',
      },
    ],
  },
  {
    id: 'customer-experience',
    title: 'Customer Experience & Retention',
    description: "How you keep customers coming back and referring others is as important as getting them.",
    fields: [
      {
        id: 'onlineBooking',
        label: 'Can customers book, schedule, or purchase from you online?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-full', label: 'Yes — fully self-serve online' },
          { value: 'yes-partial', label: 'Partially — form or request, then we confirm' },
          { value: 'no-want', label: 'No, but I want this' },
          { value: 'no', label: 'No — all handled by phone or in person' },
        ],
      },
      {
        id: 'reviewStrategy',
        label: 'Do you have a system to collect reviews after a transaction or service?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-automated', label: 'Yes — automated follow-up' },
          { value: 'yes-manual', label: 'Yes — we ask manually' },
          { value: 'no-want', label: 'No, but I know we should' },
          { value: 'no', label: 'No review process' },
        ],
      },
      {
        id: 'repeatCustomerStrategy',
        label: 'What do you do to keep customers coming back?',
        type: 'textarea',
        flag: 'upsell',
        placeholder: 'e.g. email newsletter, loyalty program, seasonal promotions, nothing formal yet...',
      },
    ],
  },
  {
    id: 'operations-tools',
    title: 'Operations & Tools',
    description: "How your business runs day-to-day and where manual work is slowing you down.",
    fields: [
      {
        id: 'currentTools',
        label: 'What software or tools do you use to run the business?',
        type: 'textarea',
        placeholder: 'e.g. QuickBooks, Google Workspace, CRM, scheduling app, spreadsheets...',
      },
      {
        id: 'biggestManualWork',
        label: 'What tasks are you or your team doing manually that you wish were automated?',
        type: 'textarea',
        flag: 'upsell',
        placeholder: 'e.g. appointment reminders, invoicing, follow-up emails, reporting...',
      },
      {
        id: 'teamSize',
        label: 'How many people are on your team (including yourself)?',
        type: 'radio',
        options: [
          { value: 'solo', label: 'Just me' },
          { value: '2-5', label: '2 – 5' },
          { value: '6-20', label: '6 – 20' },
          { value: '21-plus', label: '21+' },
        ],
      },
    ],
  },
  {
    id: 'goals-timeline',
    title: 'Goals, Timeline & Budget',
    description: "Last section — help us understand what success looks like and what you can invest.",
    fields: [
      {
        id: 'primaryGoal',
        label: 'What is your primary goal for this engagement?',
        type: 'radio',
        options: [
          { value: 'new-website', label: 'Build or rebuild a professional website' },
          { value: 'more-leads', label: 'Generate more qualified leads online' },
          { value: 'automate', label: 'Automate booking, follow-up, or internal workflows' },
          { value: 'credibility', label: 'Improve brand credibility and online presence' },
          { value: 'multiple', label: "Multiple goals — let's discuss" },
        ],
      },
      {
        id: 'launchDate',
        label: 'Is there a timeline or event driving this project?',
        type: 'text',
        placeholder: 'e.g. ASAP, within 30 days, before a launch or season...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will manage it ourselves' },
          { value: 'retainer', label: 'Monthly support retainer' },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'competitorReference',
        label: 'Is there a competitor or business in another industry whose digital presence you admire?',
        type: 'text',
        placeholder: 'Paste a URL or describe what you like about it',
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — context, blockers, or questions for our team?',
        type: 'textarea',
        placeholder: 'Nothing is too small or too broad.',
      },
    ],
  },
];
