import type { IntakeSection } from './types';

export const HOME_SERVICES_SECTIONS: IntakeSection[] = [
  {
    id: 'business-overview',
    title: 'Business Overview',
    description: "Let's start with your business, the services you offer, and how you are structured.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Mike Torres, Owner',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourbusiness.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'businessName',
        label: 'Business name',
        type: 'text',
        placeholder: 'e.g. Torres Home Services LLC',
      },
      {
        id: 'serviceCategory',
        label: 'What type of home services do you provide?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'cleaning', label: 'House cleaning / maid service' },
          { value: 'landscaping', label: 'Landscaping / lawn care' },
          { value: 'hvac', label: 'HVAC / heating & cooling' },
          { value: 'plumbing', label: 'Plumbing' },
          { value: 'electrical', label: 'Electrical' },
          { value: 'roofing', label: 'Roofing / siding' },
          { value: 'painting', label: 'Painting / drywall' },
          { value: 'handyman', label: 'Handyman / general repairs' },
          { value: 'pest-control', label: 'Pest control' },
          { value: 'pool', label: 'Pool service / maintenance' },
          { value: 'moving', label: 'Moving / hauling' },
        ],
      },
      {
        id: 'yearsInBusiness',
        label: 'How long have you been in business?',
        type: 'radio',
        options: [
          { value: 'under-2', label: 'Under 2 years' },
          { value: '2-5', label: '2 – 5 years' },
          { value: '6-15', label: '6 – 15 years' },
          { value: '15-plus', label: '15+ years' },
        ],
      },
      {
        id: 'teamSize',
        label: 'How many people are on your team?',
        type: 'radio',
        options: [
          { value: 'solo', label: 'Solo operator' },
          { value: '2-5', label: '2 – 5 employees / subcontractors' },
          { value: '6-20', label: '6 – 20 employees' },
          { value: '20-plus', label: '20+ employees' },
        ],
      },
    ],
  },
  {
    id: 'services-coverage',
    title: 'Services & Coverage Area',
    description: 'What you do and where you do it — the foundation of your local marketing strategy.',
    fields: [
      {
        id: 'serviceArea',
        label: 'What geographic area do you serve?',
        type: 'text',
        placeholder: 'e.g. Greater Austin metro, 30-mile radius from downtown Dallas...',
      },
      {
        id: 'serviceModel',
        label: 'How do you primarily deliver services?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'one-time', label: 'One-time jobs / projects' },
          { value: 'recurring', label: 'Recurring / subscription service' },
          { value: 'emergency', label: 'Emergency / same-day calls' },
          { value: 'commercial', label: 'Commercial / property management' },
          { value: 'residential', label: 'Residential only' },
        ],
      },
      {
        id: 'licensedInsured',
        label: 'Are you licensed and insured?',
        type: 'radio',
        options: [
          { value: 'yes-both', label: 'Yes — licensed and insured' },
          { value: 'insured-only', label: 'Insured but not licensed (where not required)' },
          { value: 'neither', label: 'Working toward licensing / insurance' },
        ],
      },
      {
        id: 'seasonality',
        label: 'Does your business have significant seasonal peaks?',
        type: 'radio',
        options: [
          { value: 'yes-major', label: 'Yes — major seasonal swings' },
          { value: 'yes-moderate', label: 'Moderate seasonality' },
          { value: 'no', label: 'Fairly consistent year-round' },
        ],
      },
    ],
  },
  {
    id: 'lead-gen-booking',
    title: 'Lead Generation & Booking',
    description: 'How homeowners find you and what happens when they want to hire you.',
    fields: [
      {
        id: 'leadSources',
        label: 'Where do most new jobs come from?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'referrals', label: 'Word of mouth / referrals' },
          { value: 'google', label: 'Google search / local SEO' },
          { value: 'nextdoor', label: 'Nextdoor / neighborhood apps' },
          { value: 'homeadvisor', label: 'HomeAdvisor / Angi / Thumbtack' },
          { value: 'social-media', label: 'Social media (Facebook, Instagram)' },
          { value: 'yard-signs', label: 'Yard signs / vehicle wraps' },
          { value: 'repeat-clients', label: 'Repeat / recurring clients' },
        ],
      },
      {
        id: 'bookingProcess',
        label: 'How do customers currently book or request a quote?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'online-form', label: 'Online form on website' },
          { value: 'online-scheduler', label: 'Online scheduler (Calendly, Jobber, etc.)' },
          { value: 'phone-only', label: 'Phone call only' },
          { value: 'text-social', label: 'Text or social media DM' },
          { value: 'no-process', label: 'No formal process' },
        ],
      },
      {
        id: 'responseTime',
        label: 'How quickly do you typically respond to new inquiries?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'under-1hr', label: 'Under 1 hour' },
          { value: 'same-day', label: 'Same business day' },
          { value: 'next-day', label: 'Next business day' },
          { value: 'slow', label: 'More than 24 hours — we know this is a problem' },
        ],
      },
      {
        id: 'leadPain',
        label: 'Where do you lose the most leads in the sales process?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. slow to respond, no online booking, prospects go with a competitor, cannot give a quick estimate...',
      },
    ],
  },
  {
    id: 'digital-reviews',
    title: 'Digital Presence & Reviews',
    description: 'For home services, your Google reviews and local visibility are often your biggest sales tool.',
    fields: [
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — professional, drives leads' },
          { value: 'adequate', label: 'Adequate — exists but underperforms' },
          { value: 'outdated', label: 'Outdated — needs a full rebuild' },
          { value: 'none', label: 'No website — Google Business Profile only' },
        ],
      },
      {
        id: 'websitePain',
        label: 'What frustrates you most about your current online presence?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. no way to request a quote online, bad on phones, no photos of our work, not showing up in Google...',
      },
      {
        id: 'googleProfile',
        label: 'Is your Google Business Profile actively managed?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — photos, posts, and reviews actively managed' },
          { value: 'yes-basic', label: 'Set up but not regularly updated' },
          { value: 'no', label: 'No — not actively managed' },
        ],
      },
      {
        id: 'reviewCount',
        label: 'Approximately how many Google reviews do you have?',
        type: 'radio',
        options: [
          { value: 'under-10', label: 'Under 10' },
          { value: '10-50', label: '10 – 50' },
          { value: '50-200', label: '50 – 200' },
          { value: '200-plus', label: '200+' },
        ],
      },
      {
        id: 'reviewStrategy',
        label: 'Do you have a system to ask customers for reviews after a job?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-automated', label: 'Yes — automated text or email follow-up' },
          { value: 'yes-manual', label: 'Yes — we ask in person or by text' },
          { value: 'no-want', label: 'No — but we know we should' },
          { value: 'no', label: 'No review strategy' },
        ],
      },
      {
        id: 'beforeAfterPhotos',
        label: 'Do you showcase before/after photos or project galleries online?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-strong', label: 'Yes — strong gallery on website or social' },
          { value: 'yes-weak', label: 'Yes — but limited or outdated' },
          { value: 'no-want', label: 'No — but we want to showcase our work' },
          { value: 'no', label: 'No project photos online' },
        ],
      },
    ],
  },
  {
    id: 'pricing-estimates',
    title: 'Pricing & Estimates',
    description: 'How you price and quote jobs affects conversion rates and customer expectations.',
    fields: [
      {
        id: 'pricingModel',
        label: 'How do you primarily price your services?',
        type: 'radio',
        options: [
          { value: 'flat-rate', label: 'Flat rate / package pricing' },
          { value: 'hourly', label: 'Hourly rate' },
          { value: 'custom-quote', label: 'Custom quote per job (site visit required)' },
          { value: 'mix', label: 'Mix of models' },
        ],
      },
      {
        id: 'pricingVisible',
        label: 'Is your pricing visible to customers before they contact you?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — pricing published on website' },
          { value: 'ranges', label: 'Price ranges or starting-at pricing shown' },
          { value: 'no-want', label: 'No — but we want to be more transparent' },
          { value: 'no', label: 'No — all pricing is quote-based' },
        ],
      },
      {
        id: 'estimateProcess',
        label: 'How do you deliver estimates to prospective customers?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'digital-automated', label: 'Digital estimate sent automatically' },
          { value: 'digital-manual', label: 'Digital — but requires manual creation' },
          { value: 'verbal', label: 'Verbal quote on site or by phone' },
          { value: 'no-process', label: 'No formal estimate process' },
        ],
      },
      {
        id: 'thirdPartyFees',
        label: 'Are you paying for leads through HomeAdvisor, Angi, or similar platforms?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'yes-significant', label: 'Yes — significant spend, mixed results' },
          { value: 'yes-minor', label: 'Yes — minor spend' },
          { value: 'no-tried', label: 'No — tried it and stopped' },
          { value: 'no', label: 'No — never used lead platforms' },
        ],
      },
    ],
  },
  {
    id: 'operations-scheduling',
    title: 'Operations & Scheduling',
    description: 'The tools and processes that keep jobs on track and customers informed.',
    fields: [
      {
        id: 'fieldServiceSoftware',
        label: 'What field service or job management software do you use?',
        type: 'radio',
        options: [
          { value: 'jobber', label: 'Jobber' },
          { value: 'housecall-pro', label: 'Housecall Pro' },
          { value: 'servicetitan', label: 'ServiceTitan' },
          { value: 'fieldpulse', label: 'FieldPulse' },
          { value: 'quickbooks', label: 'QuickBooks (invoicing only)' },
          { value: 'spreadsheets', label: 'Spreadsheets / manual tracking' },
          { value: 'none', label: 'No software currently' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        id: 'customerCommunication',
        label: 'How do you communicate with customers about job status and scheduling?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'automated-text', label: 'Automated text updates (on the way, completed)' },
          { value: 'phone', label: 'Phone calls' },
          { value: 'email', label: 'Email' },
          { value: 'app', label: 'Customer app or portal' },
          { value: 'none', label: 'Minimal communication' },
        ],
      },
      {
        id: 'biggestOpsPain',
        label: 'What is your single biggest operational challenge today?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. scheduling conflicts, no-shows, invoicing delays, crew communication, route optimization...',
      },
      {
        id: 'paymentMethods',
        label: 'What payment methods do you accept?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'credit-card', label: 'Credit / debit card' },
          { value: 'ach', label: 'ACH / bank transfer' },
          { value: 'cash', label: 'Cash' },
          { value: 'check', label: 'Check' },
          { value: 'financing', label: 'Customer financing options' },
        ],
      },
    ],
  },
  {
    id: 'timeline-budget',
    title: 'Timeline, Budget & Final Thoughts',
    description: "Last section — let's align on priorities and investment level.",
    fields: [
      {
        id: 'primaryGoal',
        label: 'What is your primary goal for this engagement?',
        type: 'radio',
        options: [
          { value: 'new-website', label: 'Build or rebuild a professional website' },
          { value: 'more-leads', label: 'Generate more qualified leads online' },
          { value: 'online-booking', label: 'Add online booking or quote requests' },
          { value: 'reviews-reputation', label: 'Improve Google reviews and local visibility' },
          { value: 'streamline-ops', label: 'Streamline scheduling and customer communication' },
          { value: 'multiple', label: "Multiple goals — let's discuss" },
        ],
      },
      {
        id: 'launchDate',
        label: 'Is there a busy season or deadline driving this project?',
        type: 'text',
        placeholder: 'e.g. before spring rush, before expanding to a new area, ASAP...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will handle it ourselves' },
          { value: 'retainer', label: 'Monthly support retainer' },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'brandIdentity',
        label: 'Do you have an established brand identity (logo, colors, fonts)?',
        type: 'radio',
        options: [
          { value: 'established', label: "Yes — brand is solid, don't change it" },
          { value: 'refresh', label: 'Yes — but open to a refresh' },
          { value: 'need-help', label: 'No — we need full branding help' },
        ],
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — goals, frustrations, or questions for our team?',
        type: 'textarea',
        placeholder: 'No detail is too small.',
      },
    ],
  },
];
