import type { IntakeSection } from './types';

export const INSURANCE_SECTIONS: IntakeSection[] = [
  {
    id: 'agency-overview',
    title: 'Agency Overview',
    description: "Let's start with your agency structure, team, and the markets you serve.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Rachel Kim, Agency Principal',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@youragency.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'agencyName',
        label: 'Agency or brokerage name',
        type: 'text',
        placeholder: 'e.g. Harbor Point Insurance Group',
      },
      {
        id: 'agencyType',
        label: 'What best describes your agency?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'independent', label: 'Independent agency' },
          { value: 'captive', label: 'Captive agency (single carrier)' },
          { value: 'mga', label: 'MGA / wholesale broker' },
          { value: 'benefits', label: 'Employee benefits specialist' },
          { value: 'life-health', label: 'Life & health focused' },
          { value: 'p-c', label: 'Property & casualty focused' },
        ],
      },
      {
        id: 'teamSize',
        label: 'How many producers or agents are on your team?',
        type: 'radio',
        options: [
          { value: 'solo', label: 'Solo producer' },
          { value: '2-5', label: '2 – 5 producers' },
          { value: '6-20', label: '6 – 20 producers' },
          { value: '20-plus', label: '20+ producers' },
        ],
      },
      {
        id: 'clientCount',
        label: 'Approximately how many active clients or policies do you manage?',
        type: 'radio',
        options: [
          { value: 'under-100', label: 'Under 100' },
          { value: '100-500', label: '100 – 500' },
          { value: '500-2000', label: '500 – 2,000' },
          { value: '2000-plus', label: '2,000+' },
        ],
      },
    ],
  },
  {
    id: 'products-lines',
    title: 'Products & Lines of Business',
    description: 'The lines you write determine how your website and client tools should be structured.',
    fields: [
      {
        id: 'linesOfBusiness',
        label: 'Which lines of business do you primarily write?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'personal-auto', label: 'Personal auto' },
          { value: 'homeowners', label: 'Homeowners / renters' },
          { value: 'commercial-p-c', label: 'Commercial P&C' },
          { value: 'life', label: 'Life insurance' },
          { value: 'health', label: 'Health / Medicare' },
          { value: 'workers-comp', label: "Workers' compensation" },
          { value: 'umbrella', label: 'Umbrella / excess liability' },
          { value: 'specialty', label: 'Specialty lines (marine, aviation, etc.)' },
        ],
      },
      {
        id: 'carrierCount',
        label: 'How many carrier appointments do you hold?',
        type: 'radio',
        options: [
          { value: '1-3', label: '1 – 3 carriers' },
          { value: '4-10', label: '4 – 10 carriers' },
          { value: '11-25', label: '11 – 25 carriers' },
          { value: '25-plus', label: '25+ carriers' },
        ],
      },
      {
        id: 'nicheFocus',
        label: 'Do you specialize in a particular industry or client type?',
        type: 'text',
        placeholder: 'e.g. contractors, restaurants, nonprofits, high-net-worth individuals...',
      },
      {
        id: 'quoteProcess',
        label: 'How do prospects currently request a quote?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'online-form', label: 'Online form on website' },
          { value: 'phone-email', label: 'Phone or email only' },
          { value: 'rater-tool', label: 'Online rater / comparative quote tool' },
          { value: 'walk-in', label: 'Walk-in / referral only' },
        ],
      },
    ],
  },
  {
    id: 'lead-gen-crm',
    title: 'Lead Generation & CRM',
    description: 'How you attract and track prospects before they become clients.',
    fields: [
      {
        id: 'leadSources',
        label: 'Where do most new clients come from?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'referrals', label: 'Client referrals' },
          { value: 'google', label: 'Google search / local SEO' },
          { value: 'carrier-leads', label: 'Carrier lead programs' },
          { value: 'networking', label: 'Networking / community involvement' },
          { value: 'social-media', label: 'Social media' },
          { value: 'paid-ads', label: 'Paid ads (Google, Facebook)' },
          { value: 'cross-sell', label: 'Cross-sell from existing book' },
        ],
      },
      {
        id: 'crmSystem',
        label: 'What CRM or agency management system do you use?',
        type: 'radio',
        options: [
          { value: 'applied-epic', label: 'Applied Epic' },
          { value: 'ams360', label: 'AMS360 (Vertafore)' },
          { value: 'hawksoft', label: 'HawkSoft' },
          { value: 'agencyzoom', label: 'AgencyZoom' },
          { value: 'salesforce', label: 'Salesforce' },
          { value: 'spreadsheets', label: 'Spreadsheets / manual tracking' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        id: 'leadFollowUp',
        label: 'Do you have an automated follow-up process for new leads?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-automated', label: 'Yes — automated email/SMS sequences' },
          { value: 'yes-manual', label: 'Yes — but manual / inconsistent' },
          { value: 'no-want', label: 'No — and we want to add this' },
          { value: 'no', label: 'No follow-up system' },
        ],
      },
      {
        id: 'leadPain',
        label: 'Where do you lose the most prospects in the sales process?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. slow quote turnaround, no follow-up after initial contact, prospects go with a competitor...',
      },
    ],
  },
  {
    id: 'digital-compliance',
    title: 'Digital Presence & Compliance',
    description: 'Insurance marketing has unique compliance requirements — your site needs to reflect that.',
    fields: [
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — professional, compliant, drives leads' },
          { value: 'adequate', label: 'Adequate — functional but dated' },
          { value: 'outdated', label: 'Outdated — needs a full rebuild' },
          { value: 'none', label: 'No website currently' },
        ],
      },
      {
        id: 'websitePain',
        label: 'What frustrates you most about your current website?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. not mobile-friendly, no quote form, carrier logos outdated, compliance disclaimers missing...',
      },
      {
        id: 'complianceConcerns',
        label: 'Which compliance considerations are most important for your site?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'state-licensing', label: 'State licensing disclosures' },
          { value: 'carrier-approval', label: 'Carrier marketing approval requirements' },
          { value: 'hipaa', label: 'HIPAA (health/benefits lines)' },
          { value: 'tcpa', label: 'TCPA / consent for communications' },
          { value: 'accessibility', label: 'ADA / web accessibility' },
          { value: 'not-sure', label: 'Not sure — need guidance' },
        ],
      },
      {
        id: 'googleProfile',
        label: 'Is your Google Business Profile actively managed?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — photos, hours, and reviews are current' },
          { value: 'partial', label: 'Set up but not regularly maintained' },
          { value: 'no', label: 'No — not actively managed' },
        ],
      },
    ],
  },
  {
    id: 'client-experience',
    title: 'Client Experience & Retention',
    description: 'Keeping clients engaged between renewals is where agencies win or lose long-term revenue.',
    fields: [
      {
        id: 'clientPortal',
        label: 'Do clients have a self-service portal to view policies, documents, or make payments?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-robust', label: 'Yes — robust client portal' },
          { value: 'yes-basic', label: 'Yes — basic / carrier-provided portal' },
          { value: 'no-want', label: 'No — and we want to add this' },
          { value: 'no', label: 'No client portal' },
        ],
      },
      {
        id: 'renewalProcess',
        label: 'How do you handle policy renewals and annual reviews?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. automated reminders, manual outreach, clients renew without contact...',
      },
      {
        id: 'certificateRequests',
        label: 'How do clients request certificates of insurance (COIs)?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'online-self-serve', label: 'Online self-service' },
          { value: 'email-request', label: 'Email request to agency' },
          { value: 'phone-only', label: 'Phone call only' },
          { value: 'no-process', label: 'No formal process' },
        ],
      },
      {
        id: 'clientCommunication',
        label: 'How do you communicate with clients between renewals?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'email-newsletter', label: 'Email newsletter' },
          { value: 'annual-review', label: 'Annual policy review calls' },
          { value: 'social-media', label: 'Social media updates' },
          { value: 'sms', label: 'SMS / text alerts' },
          { value: 'none', label: 'Minimal communication between renewals' },
        ],
      },
    ],
  },
  {
    id: 'technology-stack',
    title: 'Technology Stack',
    description: 'The tools your team uses daily — and where gaps create friction.',
    fields: [
      {
        id: 'amsIntegration',
        label: 'Is your website integrated with your agency management system?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — leads and data flow automatically' },
          { value: 'partial', label: 'Partially — some manual steps' },
          { value: 'no-want', label: 'No — and we want integration' },
          { value: 'no', label: 'No integration' },
        ],
      },
      {
        id: 'eSignature',
        label: 'Do you use e-signature for applications and policy documents?',
        type: 'radio',
        options: [
          { value: 'yes', label: 'Yes — DocuSign, HelloSign, or similar' },
          { value: 'partial', label: 'Sometimes — not standardized' },
          { value: 'no', label: 'No — paper only' },
        ],
      },
      {
        id: 'paymentProcessing',
        label: 'Can clients pay premiums online through your website or portal?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — integrated payment processing' },
          { value: 'carrier-portal', label: 'Through carrier portal only' },
          { value: 'no-want', label: 'No — but we want to add this' },
          { value: 'no', label: 'No online payments' },
        ],
      },
      {
        id: 'techPain',
        label: 'What is your biggest technology pain point today?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. duplicate data entry, no single client view, outdated website CMS, carrier portal confusion...',
      },
    ],
  },
  {
    id: 'timeline-budget',
    title: 'Timeline, Budget & Final Thoughts',
    description: "Last section — let's align on priorities and investment level.",
    fields: [
      {
        id: 'primaryGoal',
        label: 'What is your primary goal for this engagement?',
        type: 'radio',
        options: [
          { value: 'new-website', label: 'Build or rebuild a professional, compliant website' },
          { value: 'more-leads', label: 'Generate more qualified leads online' },
          { value: 'client-portal', label: 'Add or improve a client self-service portal' },
          { value: 'crm-integration', label: 'Integrate website with CRM / AMS' },
          { value: 'seo-local', label: 'Improve local search visibility' },
          { value: 'multiple', label: "Multiple goals — let's discuss" },
        ],
      },
      {
        id: 'launchDate',
        label: 'Is there a deadline driving this project?',
        type: 'text',
        placeholder: 'e.g. before open enrollment, before agency anniversary, ASAP...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will handle it ourselves' },
          { value: 'retainer', label: 'Monthly support retainer' },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'brandIdentity',
        label: 'Do you have an established brand identity (logo, colors, fonts)?',
        type: 'radio',
        options: [
          { value: 'established', label: "Yes — brand is solid, don't change it" },
          { value: 'refresh', label: 'Yes — but open to a refresh' },
          { value: 'need-help', label: 'No — we need full branding help' },
        ],
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — goals, frustrations, or questions for our team?',
        type: 'textarea',
        placeholder: 'No detail is too small.',
      },
    ],
  },
];
