import type { IntakeSection } from './types';

export const JUNK_REMOVAL_SECTIONS: IntakeSection[] = [
  {
    id: 'business-overview',
    title: 'Your Business',
    description: "Let's start with who you are and how your operation is set up.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. DeShawn Brown, Owner / Operator',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourcompany.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'businessName',
        label: 'Business name',
        type: 'text',
        placeholder: 'e.g. ClearOut Junk Removal',
      },
      {
        id: 'serviceTypes',
        label: 'What services do you offer?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'residential', label: 'Residential junk removal' },
          { value: 'commercial', label: 'Commercial / office cleanouts' },
          { value: 'construction-debris', label: 'Construction debris / renovation cleanouts' },
          { value: 'estate-cleanout', label: 'Estate cleanouts' },
          { value: 'appliance-removal', label: 'Appliance removal' },
          { value: 'furniture-removal', label: 'Furniture removal' },
          { value: 'dumpster-rental', label: 'Dumpster rental / roll-off' },
          { value: 'same-day', label: 'Same-day or emergency service' },
        ],
      },
      {
        id: 'truckCount',
        label: 'How many trucks / crews do you operate?',
        type: 'radio',
        options: [
          { value: 'one', label: '1 truck' },
          { value: 'two-five', label: '2 – 5 trucks' },
          { value: 'six-plus', label: '6+ trucks' },
        ],
      },
      {
        id: 'serviceArea',
        label: 'What area do you serve?',
        type: 'text',
        placeholder: 'e.g. Greater Dallas–Fort Worth, Bay Area + surrounding counties...',
      },
    ],
  },
  {
    id: 'lead-booking',
    title: 'Lead Capture & Job Booking',
    description: "How new jobs find you — and how they turn into booked appointments — is your revenue engine.",
    fields: [
      {
        id: 'leadSources',
        label: 'Where do most of your new customers come from?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'google-search', label: 'Google search / local SEO' },
          { value: 'yelp', label: 'Yelp' },
          { value: 'thumbtack-angi', label: 'Thumbtack / Angi / HomeAdvisor' },
          { value: 'google-lsa', label: 'Google Local Service Ads' },
          { value: 'referrals', label: 'Word of mouth / referrals' },
          { value: 'social-media', label: 'Social media' },
          { value: 'direct-mail', label: 'Door hangers / direct mail' },
          { value: 'repeat-customers', label: 'Repeat customers' },
        ],
      },
      {
        id: 'bookingProcess',
        label: 'How do customers currently book a job?',
        type: 'radio',
        options: [
          { value: 'online-instant', label: 'Online — instant booking with pricing calculator' },
          { value: 'online-form', label: 'Online form — we follow up to confirm' },
          { value: 'phone-text', label: 'Phone or text only' },
          { value: 'mix', label: 'Mix of online and phone' },
        ],
      },
      {
        id: 'onlineQuoting',
        label: 'Can customers get an estimate or price range online without calling?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-instant', label: 'Yes — instant online estimate or pricing calculator' },
          { value: 'yes-form', label: 'Yes — they submit a form and we respond with a quote' },
          { value: 'no-want', label: 'No, but customers keep asking for this' },
          { value: 'no', label: 'No — all quotes are done in person or by phone' },
        ],
      },
      {
        id: 'bookingPlatform',
        label: 'What tool or platform do you use to manage bookings and scheduling?',
        type: 'text',
        flag: 'pain',
        placeholder: 'e.g. Jobber, Housecall Pro, ServiceTitan, Google Calendar, pen and paper...',
      },
      {
        id: 'noShowRate',
        label: 'Do you have a significant problem with no-shows or last-minute cancellations?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'yes-big-problem', label: 'Yes — it costs us real money' },
          { value: 'occasional', label: 'Occasionally — manageable but annoying' },
          { value: 'no', label: 'No — not a major issue' },
        ],
      },
    ],
  },
  {
    id: 'digital-presence',
    title: 'Digital Presence',
    description: "Your website and local listings are often the first impression. Let's assess where you stand.",
    fields: [
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — professional, gets leads consistently' },
          { value: 'adequate', label: 'Functional but not impressive' },
          { value: 'outdated', label: 'Outdated — definitely needs a rebuild' },
          { value: 'none', label: 'No website currently' },
        ],
      },
      {
        id: 'googleProfile',
        label: 'Is your Google Business Profile active and regularly updated?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — photos, reviews, and hours are current' },
          { value: 'partial', label: 'Partially set up — some info missing' },
          { value: 'no', label: 'No — not actively managed' },
        ],
      },
      {
        id: 'reviewCount',
        label: 'Approximately how many Google reviews do you have?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'under-25', label: 'Under 25' },
          { value: '25-100', label: '25 – 100' },
          { value: '100-250', label: '100 – 250' },
          { value: '250-plus', label: '250+' },
        ],
      },
      {
        id: 'reviewStrategy',
        label: 'Do you have a system to ask customers for reviews after a job?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-automated', label: 'Yes — automated text or email follow-up' },
          { value: 'yes-manual', label: 'Yes — we ask manually' },
          { value: 'no-want', label: 'No, but I know we should' },
          { value: 'no', label: 'No review strategy currently' },
        ],
      },
    ],
  },
  {
    id: 'pricing-payments',
    title: 'Pricing & Payments',
    description: "Transparent pricing and fast payment collection set you apart from competitors.",
    fields: [
      {
        id: 'pricingModel',
        label: 'How do you structure your pricing?',
        type: 'radio',
        options: [
          { value: 'flat-rate', label: 'Flat rate by job size or item type' },
          { value: 'truck-load', label: 'By truck load fraction (1/4, 1/2, full)' },
          { value: 'hourly', label: 'Hourly labor rate' },
          { value: 'custom-quote', label: 'Custom quote for every job' },
          { value: 'mix', label: 'Mix of the above' },
        ],
      },
      {
        id: 'paymentMethods',
        label: 'What payment methods do you currently accept?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'credit-card', label: 'Credit / debit card (in-person or online)' },
          { value: 'cash', label: 'Cash' },
          { value: 'check', label: 'Check' },
          { value: 'venmo-zelle', label: 'Venmo / Zelle / CashApp' },
          { value: 'invoice-net', label: 'Invoice with net terms (commercial)' },
        ],
      },
      {
        id: 'depositPolicy',
        label: 'Do you collect a deposit or payment upfront to secure a booking?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-deposit', label: 'Yes — deposit required at booking' },
          { value: 'yes-full', label: 'Yes — full payment upfront' },
          { value: 'no-want', label: 'No, but I want to start doing this' },
          { value: 'no', label: 'No deposit — pay on job completion' },
        ],
      },
    ],
  },
  {
    id: 'operations-growth',
    title: 'Operations & Growth',
    description: 'How you run the business day-to-day and where you want to take it.',
    fields: [
      {
        id: 'dispatchProcess',
        label: 'How do you dispatch crews and communicate jobs to your team?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. text message, phone call, whiteboard, scheduling app, group chat...',
      },
      {
        id: 'beforeAfterPhotos',
        label: 'Do you document jobs with before and after photos?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-always', label: 'Yes — always, for every job' },
          { value: 'sometimes', label: 'Sometimes — not consistently' },
          { value: 'no', label: 'No — we don\'t take job photos' },
        ],
      },
      {
        id: 'growthGoal',
        label: 'What is your biggest growth goal for the next 12 months?',
        type: 'radio',
        options: [
          { value: 'more-leads', label: 'More inbound leads and booked jobs' },
          { value: 'more-trucks', label: 'Add trucks / expand capacity' },
          { value: 'commercial-clients', label: 'Win more commercial or recurring contracts' },
          { value: 'systemize', label: 'Systemize and reduce owner dependency' },
          { value: 'multiple', label: 'All of the above' },
        ],
      },
      {
        id: 'biggestPain',
        label: 'What is your single biggest operational pain point right now?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. phone is ringing too much, no-shows, crews not knowing job details, invoicing delays...',
      },
    ],
  },
  {
    id: 'timeline-budget',
    title: 'Timeline, Budget & Final Thoughts',
    description: 'Last section — help us understand priorities and investment level.',
    fields: [
      {
        id: 'launchDate',
        label: 'Is there a timeline driving this project?',
        type: 'text',
        placeholder: 'e.g. spring busy season, ASAP, within 60 days...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will handle it ourselves' },
          { value: 'retainer', label: 'Monthly support retainer' },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'competitorReference',
        label: 'Is there a competitor or local junk removal company whose online presence you admire?',
        type: 'text',
        placeholder: 'Paste a URL or describe what you like about their site',
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — goals, blockers, or questions for our team?',
        type: 'textarea',
        placeholder: 'No detail is too small.',
      },
    ],
  },
];
