import type { IntakeSection } from './types';

export const LOGISTICS_SECTIONS: IntakeSection[] = [
  {
    id: 'company-services',
    title: 'Company & Services Overview',
    description: "Let's start with who you are and what your logistics operation looks like.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Marcus Davis, VP of Operations',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourcompany.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'companyName',
        label: 'Company name',
        type: 'text',
        placeholder: 'e.g. Apex Freight Solutions',
      },
      {
        id: 'serviceType',
        label: 'What best describes your logistics operation?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'freight-broker', label: 'Freight brokerage' },
          { value: 'asset-trucking', label: 'Asset-based trucking / carrier' },
          { value: '3pl', label: 'Third-party logistics (3PL) / fulfillment center' },
          { value: 'last-mile', label: 'Last-mile delivery' },
          { value: 'drayage', label: 'Drayage / port operations' },
          { value: 'warehousing', label: 'Warehousing & distribution' },
          { value: 'cold-chain', label: 'Cold chain / temperature-controlled' },
          { value: 'freight-forwarding', label: 'International freight forwarding / customs' },
        ],
      },
      {
        id: 'fleetOrNetworkSize',
        label: 'What is the approximate scale of your operation?',
        type: 'radio',
        options: [
          { value: 'small', label: 'Small (1 – 10 trucks / carriers or < 50 shipments/month)' },
          { value: 'mid', label: 'Mid-size (11 – 100 trucks / 50 – 500 shipments/month)' },
          { value: 'large', label: 'Large (100+ trucks / 500+ shipments/month)' },
          { value: 'enterprise', label: 'Enterprise / national network' },
        ],
      },
    ],
  },
  {
    id: 'current-systems',
    title: 'Current Systems & Technology',
    description: "We need to understand your current stack before we can make meaningful recommendations.",
    fields: [
      {
        id: 'tms',
        label: 'What TMS (Transportation Management System) are you using?',
        type: 'radio',
        options: [
          { value: 'mcleod', label: 'McLeod Software' },
          { value: 'mercurygate', label: 'MercuryGate' },
          { value: 'inet', label: 'iNET / TMW' },
          { value: 'samsara', label: 'Samsara' },
          { value: 'custom', label: 'Custom-built system' },
          { value: 'spreadsheets', label: 'Spreadsheets / manual tracking' },
          { value: 'none', label: 'No TMS currently' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        id: 'ediCapability',
        label: 'Do you have EDI (Electronic Data Interchange) capabilities?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-full', label: 'Yes — full EDI with major shippers/retailers' },
          { value: 'yes-limited', label: 'Yes — limited EDI capability' },
          { value: 'no-want', label: 'No, but shippers/customers are asking for it' },
          { value: 'no', label: 'No EDI — not required for our customers' },
        ],
      },
      {
        id: 'trackingVisibility',
        label: 'How do you provide shipment tracking visibility to your customers today?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'customer-portal', label: 'Dedicated customer tracking portal' },
          { value: 'email-updates', label: 'Manual email / phone updates' },
          { value: 'third-party', label: 'Third-party tracking link (FourKites, Project44, etc.)' },
          { value: 'none', label: 'No formal tracking visibility offered' },
        ],
      },
      {
        id: 'systemIntegration',
        label: 'What are your current biggest technology pain points?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. no real-time tracking for customers, manual quoting, data siloed across systems...',
      },
    ],
  },
  {
    id: 'customer-facing-tools',
    title: 'Customer-Facing Tools & Portal',
    description: "Your customers judge your operation by how easy you are to work with digitally.",
    fields: [
      {
        id: 'onlineQuoting',
        label: 'Can customers get a freight quote online?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-instant', label: 'Yes — instant online quoting tool' },
          { value: 'yes-form', label: 'Yes — quote request form, we respond manually' },
          { value: 'no-want', label: 'No — and customers keep asking for this' },
          { value: 'no', label: 'No — all quotes are done over phone/email' },
        ],
      },
      {
        id: 'onlineBooking',
        label: 'Can customers book or schedule a pickup / shipment online?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — self-service booking is live' },
          { value: 'want', label: 'No, but we want to offer this' },
          { value: 'no', label: 'No — booking is handled manually' },
        ],
      },
      {
        id: 'customerPortal',
        label: 'Do your customers have a portal to manage their shipments, invoices, or documents?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-full', label: 'Yes — full self-service customer portal' },
          { value: 'yes-limited', label: 'Yes — limited portal (tracking only, etc.)' },
          { value: 'no-want', label: 'No — customers are asking for one' },
          { value: 'no', label: 'No portal — all managed via email / phone' },
        ],
      },
      {
        id: 'documentManagement',
        label: 'How are BOLs, PODs, and other freight documents handled today?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'digital-automated', label: 'Fully digital — auto-generated and emailed' },
          { value: 'digital-manual', label: 'Digital but uploaded manually' },
          { value: 'paper', label: 'Paper-based with manual scanning' },
          { value: 'mix', label: 'Mix of digital and paper' },
        ],
      },
    ],
  },
  {
    id: 'operations-integrations',
    title: 'Operations & System Integrations',
    description: "How well does your tech stack talk to each other — and to your customers' systems?",
    fields: [
      {
        id: 'erpIntegration',
        label: 'Do you integrate with customers ERP or WMS systems (SAP, Oracle, NetSuite, etc.)?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — API or EDI integrations are in place' },
          { value: 'some', label: 'Some — case-by-case for large customers' },
          { value: 'no-want', label: 'No — but enterprise customers are requesting this' },
          { value: 'no', label: 'No integrations currently' },
        ],
      },
      {
        id: 'dispatchProcess',
        label: 'How is dispatch and load assignment handled today?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. dispatcher phone calls, board in the office, TMS load board, driver app...',
      },
      {
        id: 'driverApp',
        label: 'Do drivers use a mobile app for updates, PODs, or communication?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — drivers use a dedicated app' },
          { value: 'no-want', label: 'No — we want to streamline this' },
          { value: 'no', label: 'No driver app currently' },
        ],
      },
      {
        id: 'automationOpportunities',
        label: 'What repetitive tasks are your team doing manually that you wish were automated?',
        type: 'textarea',
        flag: 'upsell',
        placeholder: 'e.g. check calls, status emails, invoice generation, load tendering...',
      },
    ],
  },
  {
    id: 'sales-lead-capture',
    title: 'Sales & Lead Capture',
    description: "How are you bringing in new shippers and growing revenue?",
    fields: [
      {
        id: 'leadSources',
        label: 'Where do your new customers primarily come from?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'referrals', label: 'Referrals from existing customers' },
          { value: 'cold-outreach', label: 'Cold outreach / sales team' },
          { value: 'broker-load-boards', label: 'Load boards (DAT, Truckstop, etc.)' },
          { value: 'website-inbound', label: 'Website inbound / SEO' },
          { value: 'trade-shows', label: 'Trade shows / industry events' },
          { value: 'partnerships', label: 'Partnerships or agent network' },
          { value: 'no-formal', label: 'No formal sales/marketing strategy' },
        ],
      },
      {
        id: 'websiteLeads',
        label: 'Is your website generating inbound shipper or customer leads?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — regularly' },
          { value: 'occasionally', label: 'Occasionally' },
          { value: 'no-want', label: "No — and I want it to" },
          { value: 'no', label: 'No — not a priority' },
        ],
      },
      {
        id: 'rfpProcess',
        label: 'How do you handle RFQs and RFPs from potential customers?',
        type: 'radio',
        options: [
          { value: 'formal', label: 'Formal process with templates and a timeline' },
          { value: 'informal', label: 'Informal — we figure it out case by case' },
          { value: 'no-rfp', label: "We don't receive formal RFQs/RFPs" },
        ],
      },
      {
        id: 'marketingContent',
        label: 'Do you have up-to-date marketing materials (capability deck, case studies, etc.)?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — polished and current' },
          { value: 'outdated', label: 'Yes but they are outdated or need a refresh' },
          { value: 'no', label: 'No formal marketing materials' },
        ],
      },
    ],
  },
  {
    id: 'reporting-visibility',
    title: 'Reporting & Business Visibility',
    description: "The best logistics leaders run on data. Let's see where the gaps are.",
    fields: [
      {
        id: 'kpiTracking',
        label: 'Which KPIs do you currently track?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'on-time-delivery', label: 'On-time delivery rate' },
          { value: 'claims-ratio', label: 'Claims ratio / freight damage rate' },
          { value: 'revenue-per-load', label: 'Revenue per load / margin per lane' },
          { value: 'driver-utilization', label: 'Driver / asset utilization' },
          { value: 'customer-satisfaction', label: 'Customer satisfaction (CSAT/NPS)' },
          { value: 'dwell-time', label: 'Dwell time / detention charges' },
          { value: 'none', label: 'No formal KPI tracking' },
        ],
      },
      {
        id: 'reportingProcess',
        label: 'How do you currently generate reports for leadership or customers?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'tms-reports', label: 'Automated from TMS / system' },
          { value: 'manual-excel', label: 'Manual Excel / spreadsheet reports' },
          { value: 'bi-tool', label: 'BI tool (Tableau, Power BI, Looker, etc.)' },
          { value: 'no-reports', label: 'No formal reporting' },
        ],
      },
      {
        id: 'dashboardWishList',
        label: 'If you had a real-time operations dashboard, what would be on it?',
        type: 'textarea',
        flag: 'upsell',
        placeholder: 'e.g. live shipment map, on-time rate, open quotes, revenue by lane, driver status...',
      },
    ],
  },
  {
    id: 'timeline-support',
    title: 'Timeline, Budget & Final Thoughts',
    description: "Let's wrap up with your timeline and what success looks like for you.",
    fields: [
      {
        id: 'launchDate',
        label: 'Is there a deadline or milestone driving this project?',
        type: 'text',
        placeholder: 'e.g. new contract starting, renewal deadline, Q3 push...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-5k', label: 'Under $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-50k', label: '$15,000 – $50,000' },
          { value: '50k-plus', label: '$50,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope and ROI' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We have internal IT — we can manage it' },
          { value: 'retainer', label: "Monthly managed service / support retainer" },
          { value: 'on-call', label: 'On-call support as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'successDefinition',
        label: 'What does success look like for you 6 months after launch?',
        type: 'textarea',
        placeholder: 'e.g. customers can self-serve tracking, sales team has better qualified leads, dispatch is 50% faster...',
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — pain points, priorities, or questions for our team?',
        type: 'textarea',
        placeholder: 'No detail is too small.',
      },
    ],
  },
];
