import type { IntakeSection } from './types';

export const REAL_ESTATE_SECTIONS: IntakeSection[] = [
  {
    id: 'about-brokerage',
    title: 'About You & Your Brokerage',
    description: "Let's start with who you are and the markets you serve.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Sarah Williams, Realtor / Team Lead',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourbrokerage.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'brokerageOrTeamName',
        label: 'Brokerage or team name',
        type: 'text',
        placeholder: 'e.g. Williams Realty Group at Keller Williams',
      },
      {
        id: 'agentProfile',
        label: 'Which best describes your business?',
        type: 'radio',
        options: [
          { value: 'solo-agent', label: 'Solo agent' },
          { value: 'small-team', label: 'Small team (2 – 5 agents)' },
          { value: 'large-team', label: 'Large team or mega-team (6+ agents)' },
          { value: 'brokerage', label: 'Independent brokerage' },
        ],
      },
      {
        id: 'markets',
        label: 'What markets / property types do you primarily serve?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'residential', label: 'Residential (single-family)' },
          { value: 'luxury', label: 'Luxury residential' },
          { value: 'condos-townhomes', label: 'Condos / townhomes' },
          { value: 'new-construction', label: 'New construction' },
          { value: 'commercial', label: 'Commercial / mixed-use' },
          { value: 'investment', label: 'Investment properties / multi-family' },
          { value: 'rental', label: 'Property management / rentals' },
        ],
      },
    ],
  },
  {
    id: 'current-site-tools',
    title: 'Current Website & Tools',
    description: "Tell us what you're working with today and what's frustrating you most.",
    fields: [
      {
        id: 'currentWebsite',
        label: 'Do you have a real estate website today?',
        type: 'radio',
        options: [
          { value: 'brokerage-provided', label: 'Yes — brokerage-provided site (e.g. Keller Williams, RE/MAX template)' },
          { value: 'custom', label: 'Yes — custom-built or third-party (Curaytor, Real Geeks, etc.)' },
          { value: 'basic', label: 'Yes — basic site, mostly a business card online' },
          { value: 'none', label: 'No website yet' },
        ],
      },
      {
        id: 'idxIntegration',
        label: 'Do you have IDX / MLS listing integration on your site?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-happy', label: 'Yes and it works well' },
          { value: 'yes-poor', label: 'Yes but the search experience is poor' },
          { value: 'no-want', label: 'No — we want to add IDX/MLS search' },
          { value: 'no', label: 'No and not needed right now' },
        ],
      },
      {
        id: 'crm',
        label: 'What CRM do you use to manage leads and clients?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'follow-up-boss', label: 'Follow Up Boss' },
          { value: 'kvcore', label: 'kvCORE' },
          { value: 'top-producer', label: 'Top Producer' },
          { value: 'hubspot', label: 'HubSpot / general CRM' },
          { value: 'spreadsheets', label: 'Spreadsheets / no formal CRM' },
          { value: 'other', label: 'Other CRM' },
        ],
      },
      {
        id: 'websitePain',
        label: 'What is the biggest pain with your current website or lead capture setup?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. Low traffic, no qualified leads from the site, IDX is slow...',
      },
    ],
  },
  {
    id: 'listings-lead-capture',
    title: 'Listings & Lead Capture',
    description: "How you present listings and capture buyer/seller leads determines your pipeline.",
    fields: [
      {
        id: 'listingPresentation',
        label: 'How do you present your active listings online?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'idx-site', label: 'IDX search on my site' },
          { value: 'zillow-realtor', label: 'Zillow / Realtor.com listings' },
          { value: 'custom-landing-pages', label: 'Custom listing landing pages' },
          { value: 'virtual-tours', label: 'Virtual tours / 3D walkthroughs (Matterport, etc.)' },
          { value: 'video-tours', label: 'Video walkthroughs on YouTube / social' },
          { value: 'no-listings', label: 'Not promoting listings online currently' },
        ],
      },
      {
        id: 'leadMagnet',
        label: 'Do you use any lead magnets or offers to capture visitor contact info?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — home valuation, market reports, buyer guides, etc.' },
          { value: 'want', label: 'No, but I want to build this out' },
          { value: 'no', label: 'No lead magnets currently' },
        ],
      },
      {
        id: 'homeValuationTool',
        label: 'Do you have a home valuation tool on your site?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — live instant valuation widget' },
          { value: 'manual', label: 'Manual CMA request form only' },
          { value: 'no-want', label: 'No, and I want to add one' },
          { value: 'no', label: 'No — not a priority' },
        ],
      },
      {
        id: 'leadVolume',
        label: 'How would you describe your current inbound lead volume from your website?',
        type: 'radio',
        options: [
          { value: 'none', label: 'Zero — site generates no leads' },
          { value: 'minimal', label: 'Minimal — a few per month' },
          { value: 'moderate', label: 'Moderate — steady flow' },
          { value: 'strong', label: "Strong — I have more leads than I can handle" },
        ],
      },
    ],
  },
  {
    id: 'audience-market',
    title: 'Audience & Target Market',
    description: "Who you're trying to reach shapes every design and copy decision.",
    fields: [
      {
        id: 'targetBuyer',
        label: 'Who is your primary target client?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'first-time-buyers', label: 'First-time homebuyers' },
          { value: 'move-up-buyers', label: 'Move-up buyers (upgrading homes)' },
          { value: 'luxury-buyers', label: 'Luxury / high-end buyers' },
          { value: 'investors', label: 'Real estate investors' },
          { value: 'relocation', label: 'Relocation buyers (corporate relo)' },
          { value: 'sellers', label: 'Home sellers / listing clients' },
          { value: 'renters', label: 'Renters / rental market' },
        ],
      },
      {
        id: 'localPresence',
        label: 'How visible is your personal brand in your local market?',
        type: 'radio',
        options: [
          { value: 'top-agent', label: 'Top of mind — I am well-known locally' },
          { value: 'growing', label: 'Growing — building recognition' },
          { value: 'new', label: 'New to the market or rebranding' },
        ],
      },
      {
        id: 'competitiveEdge',
        label: 'What differentiates you from other agents or teams in your market?',
        type: 'textarea',
        placeholder: 'e.g. hyper-local expertise, exceptional staging, investor network, negotiation skills...',
      },
      {
        id: 'testimonials',
        label: 'Do you actively collect and publish client testimonials or reviews?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — Google reviews, Zillow, site testimonials' },
          { value: 'some', label: 'Some, but not systematically' },
          { value: 'no', label: 'Not currently' },
        ],
      },
    ],
  },
  {
    id: 'content-social-proof',
    title: 'Content Strategy & Social Proof',
    description: "Consistent content turns agents into market authorities.",
    fields: [
      {
        id: 'contentOutput',
        label: 'What content do you currently produce?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'blog', label: 'Blog / neighborhood guides' },
          { value: 'instagram', label: 'Instagram content (Reels, Stories, posts)' },
          { value: 'facebook', label: 'Facebook posts / groups' },
          { value: 'youtube', label: 'YouTube videos' },
          { value: 'email-newsletter', label: 'Email newsletter / market updates' },
          { value: 'podcast', label: 'Podcast' },
          { value: 'nothing', label: 'No regular content at the moment' },
        ],
      },
      {
        id: 'contentChallenge',
        label: 'What is your biggest content challenge?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'no-time', label: "Not enough time to create consistently" },
          { value: 'no-strategy', label: "Don't know what to post or write" },
          { value: 'no-reach', label: 'Posting but not reaching the right people' },
          { value: 'no-leads', label: 'Content not converting to actual leads' },
          { value: 'none', label: 'Content is going well' },
        ],
      },
      {
        id: 'marketReports',
        label: 'Do you send local market reports or stats to your database?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-regular', label: 'Yes — monthly or quarterly' },
          { value: 'occasionally', label: 'Occasionally but not on a schedule' },
          { value: 'no-want', label: 'No, and I want to start' },
          { value: 'no', label: 'No plans for market reports' },
        ],
      },
    ],
  },
  {
    id: 'lead-nurture-automation',
    title: 'Lead Nurture & Automation',
    description: "Most leads take months to convert — your follow-up system makes the difference.",
    fields: [
      {
        id: 'followUpProcess',
        label: 'How do you currently follow up with new leads?',
        type: 'radio',
        options: [
          { value: 'automated', label: 'Automated drip sequences in my CRM' },
          { value: 'manual', label: 'Manual calls and texts' },
          { value: 'mixed', label: 'Mix of automated and manual' },
          { value: 'no-process', label: 'No formal follow-up process' },
        ],
      },
      {
        id: 'emailDrip',
        label: 'Do you have email nurture drip campaigns set up?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — automated sequences are running' },
          { value: 'want', label: 'No, but I want to set these up' },
          { value: 'no', label: 'No drip campaigns' },
        ],
      },
      {
        id: 'automationWishList',
        label: 'What follow-up or automation tasks would save you the most time?',
        type: 'textarea',
        flag: 'upsell',
        placeholder: 'e.g. auto-send market reports to leads, remind me to follow up after showings...',
      },
      {
        id: 'pastClientDatabase',
        label: 'Do you have a strategy for staying in touch with past clients?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — anniversary emails, holiday outreach, etc.' },
          { value: 'informal', label: 'Informally — no structured approach' },
          { value: 'no', label: 'No past-client nurture strategy' },
        ],
      },
    ],
  },
  {
    id: 'timeline-support',
    title: 'Timeline, Budget & Final Thoughts',
    description: "Help us understand your timeline and investment appetite.",
    fields: [
      {
        id: 'launchDate',
        label: 'Is there a deadline or event driving this project?',
        type: 'text',
        placeholder: 'e.g. Spring market, market center review, expanding team in 60 days...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing updates?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'I will manage my own updates' },
          { value: 'retainer', label: "I want a monthly care + update plan" },
          { value: 'on-call', label: 'On-call support as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'seoInterest',
        label: 'Are you interested in SEO to rank for local searches (e.g. "homes for sale in [city]")?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-priority', label: 'Yes — this is a priority for me' },
          { value: 'yes-eventually', label: 'Yes eventually but not right now' },
          { value: 'no', label: 'No — I rely on referrals and paid ads' },
        ],
      },
      {
        id: 'additionalNotes',
        label: 'Anything else you want us to know — goals, concerns, or questions?',
        type: 'textarea',
        placeholder: 'The more context the better.',
      },
    ],
  },
];
