import type { IntakeSection } from './types';

export const RESTAURANT_SECTIONS: IntakeSection[] = [
  {
    id: 'about',
    title: 'Your Restaurant & Concept',
    description: "Let's start with who you are, what you serve, and what makes your concept worth talking about.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Marcus Green, Owner / Chef',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourrestaurant.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'restaurantName',
        label: 'Restaurant or brand name',
        type: 'text',
        placeholder: 'e.g. Rosewood Kitchen & Bar',
      },
      {
        id: 'conceptType',
        label: 'What best describes your concept?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'fast-casual', label: 'Fast casual' },
          { value: 'full-service', label: 'Full-service / sit-down' },
          { value: 'fine-dining', label: 'Fine dining' },
          { value: 'quick-service', label: 'Quick service / counter service' },
          { value: 'food-truck', label: 'Food truck or pop-up' },
          { value: 'bar-lounge', label: 'Bar / lounge / nightlife' },
          { value: 'cafe-bakery', label: 'Café / bakery / coffee' },
          { value: 'ghost-kitchen', label: 'Ghost kitchen / delivery-only' },
          { value: 'buffet', label: 'Buffet or all-you-can-eat' },
        ],
      },
      {
        id: 'cuisineType',
        label: 'What cuisine or food category do you specialize in?',
        type: 'text',
        placeholder: 'e.g. Southern BBQ, Modern Mexican, Italian, Vegan, Seafood...',
      },
      {
        id: 'locationCount',
        label: 'How many locations do you operate?',
        type: 'radio',
        options: [
          { value: 'one', label: '1 location' },
          { value: 'two-five', label: '2 – 5 locations' },
          { value: 'six-plus', label: '6+ locations / franchise' },
        ],
      },
    ],
  },
  {
    id: 'digital-presence',
    title: 'Current Website & Digital Presence',
    description: "Your online presence is often the first meal someone samples. Let's see where you stand.",
    fields: [
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — professional, up to date, easy to navigate' },
          { value: 'adequate', label: 'Adequate — functional but not impressive' },
          { value: 'outdated', label: 'Outdated or embarrassing — needs a full rebuild' },
          { value: 'none', label: 'No website currently' },
        ],
      },
      {
        id: 'websitePains',
        label: 'What frustrates you most about your current site or online presence?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. menu is hard to update, no online ordering, looks bad on phones, slow loading...',
      },
      {
        id: 'googleProfile',
        label: 'Is your Google Business Profile actively managed?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — photos, hours, and menu are current' },
          { value: 'yes-partial', label: 'Set up but not regularly maintained' },
          { value: 'no', label: 'No — not actively managed' },
        ],
      },
      {
        id: 'directoryListings',
        label: 'Which listing platforms are you currently on?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'yelp', label: 'Yelp' },
          { value: 'tripadvisor', label: 'TripAdvisor' },
          { value: 'opentable', label: 'OpenTable' },
          { value: 'google', label: 'Google Maps / Business Profile' },
          { value: 'facebook', label: 'Facebook Business Page' },
          { value: 'bing', label: 'Bing Places' },
          { value: 'none', label: 'None that I actively manage' },
        ],
      },
      {
        id: 'reviewCount',
        label: 'Approximately how many Google or Yelp reviews do you have?',
        type: 'radio',
        options: [
          { value: 'under-25', label: 'Under 25' },
          { value: '25-100', label: '25 – 100' },
          { value: '100-500', label: '100 – 500' },
          { value: '500-plus', label: '500+' },
        ],
      },
      {
        id: 'reviewStrategy',
        label: 'Do you have a system to ask guests for reviews after their visit?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-automated', label: 'Yes — automated text or email follow-up' },
          { value: 'yes-manual', label: 'Yes — staff ask in person or at checkout' },
          { value: 'no-want', label: 'No, but I know we should' },
          { value: 'no', label: 'No review strategy currently' },
        ],
      },
    ],
  },
  {
    id: 'ordering-reservations',
    title: 'Online Ordering & Reservations',
    description: "Friction in ordering and reservations costs you revenue directly. Let's diagnose the gaps.",
    fields: [
      {
        id: 'onlineOrdering',
        label: 'Do you currently offer online ordering?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-own', label: 'Yes — through our own website or branded app' },
          { value: 'yes-third-party', label: 'Yes — through third-party apps only (DoorDash, Uber Eats, etc.)' },
          { value: 'both', label: 'Both own and third-party' },
          { value: 'no-want', label: 'No — and we want to add this' },
          { value: 'no', label: 'No online ordering' },
        ],
      },
      {
        id: 'deliveryPlatforms',
        label: 'Which delivery platforms are you currently on?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'doordash', label: 'DoorDash' },
          { value: 'uber-eats', label: 'Uber Eats' },
          { value: 'grubhub', label: 'Grubhub' },
          { value: 'postmates', label: 'Postmates / Uber Eats (merged)' },
          { value: 'own-delivery', label: 'Own in-house delivery' },
          { value: 'none', label: 'No delivery / dine-in only' },
        ],
      },
      {
        id: 'thirdPartyFees',
        label: 'Are third-party delivery commissions eating into your margins?',
        type: 'radio',
        flag: 'pain',
        options: [
          { value: 'yes-significant', label: 'Yes — significantly impacting profitability' },
          { value: 'yes-manageable', label: "Yes — but it's manageable" },
          { value: 'no', label: 'No — delivery fees are not a major concern' },
          { value: 'na', label: "We don't use third-party delivery" },
        ],
      },
      {
        id: 'reservations',
        label: 'How do guests currently make reservations?',
        type: 'radio',
        options: [
          { value: 'online-self-serve', label: 'Online — fully self-serve (OpenTable, Resy, own system)' },
          { value: 'phone-only', label: 'Phone only' },
          { value: 'walk-in-only', label: 'Walk-in only — no reservations' },
          { value: 'mix', label: 'Mix of online and phone' },
        ],
      },
      {
        id: 'onlineOrderingPain',
        label: 'What is the biggest friction point in your current ordering or reservation experience?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. menu is out of date on third-party apps, phone gets slammed on weekends, no-shows...',
      },
    ],
  },
  {
    id: 'menu-content',
    title: 'Menu & Content Management',
    description: "A well-presented, up-to-date menu is one of the highest-converting elements on any restaurant site.",
    fields: [
      {
        id: 'menuFormat',
        label: 'How is your menu currently presented online?',
        type: 'radio',
        options: [
          { value: 'interactive-web', label: 'Interactive web menu (searchable, with photos)' },
          { value: 'static-web', label: 'Static web page (text or image-based menu)' },
          { value: 'pdf-only', label: 'PDF only — hard to read on phones' },
          { value: 'no-online-menu', label: 'No menu online' },
        ],
      },
      {
        id: 'menuUpdateProcess',
        label: 'How often does your menu change, and how painful is updating it?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. seasonal menu, daily specials, 86\'d items — who updates it and how long does it take?',
      },
      {
        id: 'menuPhotography',
        label: 'What is the current state of your food photography?',
        type: 'radio',
        options: [
          { value: 'professional', label: 'Professional shots for most dishes' },
          { value: 'diy-decent', label: 'DIY / phone photos — presentable' },
          { value: 'needs-work', label: 'Needs significant improvement' },
          { value: 'none', label: 'No food photography currently' },
        ],
      },
      {
        id: 'dietaryFiltering',
        label: 'Do guests need to filter your menu by dietary preference?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-built-in', label: 'Yes — and we already have filtering' },
          { value: 'yes-want', label: 'Yes — and we want to add this' },
          { value: 'no', label: 'Not important for our menu' },
        ],
      },
      {
        id: 'specialsEvents',
        label: 'Do you run weekly specials, happy hour, or ticketed dining events?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-promoted', label: 'Yes — and we actively promote them' },
          { value: 'yes-not-promoted', label: 'Yes — but we do a poor job promoting them online' },
          { value: 'no', label: 'No recurring specials or events' },
        ],
      },
    ],
  },
  {
    id: 'marketing-loyalty',
    title: 'Marketing, Social & Customer Loyalty',
    description: "Getting guests through the door once is a win. Getting them back is the business.",
    fields: [
      {
        id: 'socialPlatforms',
        label: 'Which social platforms are you currently active on?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'facebook', label: 'Facebook' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'youtube', label: 'YouTube' },
          { value: 'none', label: 'Not actively posting' },
        ],
      },
      {
        id: 'emailMarketing',
        label: 'Do you have an email or SMS list you market to?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-both', label: 'Yes — email and SMS' },
          { value: 'yes-email', label: 'Yes — email only' },
          { value: 'yes-sms', label: 'Yes — SMS only' },
          { value: 'no-want', label: 'No — and I want to build one' },
          { value: 'no', label: 'No list currently' },
        ],
      },
      {
        id: 'loyaltyProgram',
        label: 'Do you have a loyalty or rewards program?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-digital', label: 'Yes — digital app or platform-based' },
          { value: 'yes-stamp', label: 'Yes — paper punch card' },
          { value: 'no-want', label: 'No — and I want to launch one' },
          { value: 'no', label: 'No loyalty program' },
        ],
      },
      {
        id: 'giftCards',
        label: 'Do you sell gift cards — physical or digital?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-both', label: 'Yes — physical and digital' },
          { value: 'yes-digital', label: 'Digital only' },
          { value: 'yes-physical', label: 'Physical only' },
          { value: 'no', label: 'No gift cards' },
        ],
      },
      {
        id: 'influencerMedia',
        label: 'Have you worked with food influencers, press, or local media?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — it\'s part of our strategy' },
          { value: 'yes-organic', label: 'Yes — organically, not intentional' },
          { value: 'no-want', label: 'No — but I want to start' },
          { value: 'no', label: 'No media or influencer activity' },
        ],
      },
    ],
  },
  {
    id: 'private-events',
    title: 'Private Dining & Events',
    description: "Private events and buyouts can represent 20-30% of revenue for the right concept. Let's see where you stand.",
    fields: [
      {
        id: 'privateEvents',
        label: 'Do you host private dining, buyouts, or corporate events?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — it\'s a significant part of our business' },
          { value: 'yes-occasional', label: 'Yes — occasionally, not heavily marketed' },
          { value: 'no-want', label: 'No — but we have the space and want to develop this' },
          { value: 'no', label: 'No private events' },
        ],
      },
      {
        id: 'eventBookingProcess',
        label: 'How are private events currently booked?',
        type: 'radio',
        options: [
          { value: 'online-form', label: 'Online inquiry form on website' },
          { value: 'phone-email', label: 'Phone or email only' },
          { value: 'no-process', label: 'No formal process — ad hoc' },
        ],
      },
      {
        id: 'eventCapacity',
        label: 'What is your private event capacity?',
        type: 'text',
        placeholder: 'e.g. up to 40 guests in the private room, full buyout for 120...',
      },
      {
        id: 'cateringOffered',
        label: 'Do you offer off-site catering in addition to on-site dining?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — it\'s an active revenue line' },
          { value: 'yes-occasionally', label: 'Yes — occasionally / by request' },
          { value: 'no-want', label: 'No — but interested in adding this' },
          { value: 'no', label: 'No off-site catering' },
        ],
      },
    ],
  },
  {
    id: 'operations',
    title: 'Operations & Technology Stack',
    description: "The right tech stack lets your team focus on hospitality instead of firefighting.",
    fields: [
      {
        id: 'posSystem',
        label: 'What POS system do you use?',
        type: 'radio',
        options: [
          { value: 'toast', label: 'Toast' },
          { value: 'square', label: 'Square for Restaurants' },
          { value: 'clover', label: 'Clover' },
          { value: 'lightspeed', label: 'Lightspeed' },
          { value: 'touchbistro', label: 'TouchBistro' },
          { value: 'revel', label: 'Revel' },
          { value: 'other', label: 'Other / custom' },
        ],
      },
      {
        id: 'reservationPlatform',
        label: 'What reservation or waitlist platform do you use (if any)?',
        type: 'text',
        placeholder: 'e.g. OpenTable, Resy, Yelp Waitlist, Tock, none...',
      },
      {
        id: 'biggestOpsPain',
        label: 'What is your single biggest operational pain point today?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. managing third-party menus is a nightmare, no-shows kill the weekend, staff scheduling chaos...',
      },
      {
        id: 'staffCount',
        label: 'Approximately how many front and back of house staff do you employ?',
        type: 'radio',
        options: [
          { value: 'under-10', label: 'Under 10' },
          { value: '10-30', label: '10 – 30' },
          { value: '31-75', label: '31 – 75' },
          { value: '75-plus', label: '75+' },
        ],
      },
    ],
  },
  {
    id: 'timeline-budget',
    title: 'Timeline, Budget & Final Thoughts',
    description: "Last section — let's wrap up with your priorities and investment level.",
    fields: [
      {
        id: 'primaryGoal',
        label: 'What is your primary goal for this engagement?',
        type: 'radio',
        options: [
          { value: 'new-website', label: 'Build or rebuild a professional website' },
          { value: 'online-ordering', label: 'Add or improve online ordering' },
          { value: 'more-traffic', label: 'Drive more foot traffic and local visibility' },
          { value: 'private-events', label: 'Grow private event / catering revenue' },
          { value: 'loyalty', label: 'Build a loyalty and repeat-guest program' },
          { value: 'multiple', label: 'Multiple goals — let\'s talk it through' },
        ],
      },
      {
        id: 'launchDate',
        label: 'Is there a deadline or season driving this project?',
        type: 'text',
        placeholder: 'e.g. before summer patio season, before a rebranding, ASAP...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will handle it ourselves' },
          { value: 'retainer', label: 'Monthly support retainer' },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'brandIdentity',
        label: 'Do you have an established brand identity (logo, colors, fonts)?',
        type: 'radio',
        options: [
          { value: 'established', label: "Yes — brand is solid, don't touch it" },
          { value: 'refresh', label: 'Yes — but open to a refresh' },
          { value: 'need-help', label: 'No — we need full branding help' },
        ],
      },
      {
        id: 'competitorReference',
        label: 'Is there a restaurant or food brand whose online presence you admire?',
        type: 'text',
        placeholder: 'Paste a URL or describe what draws you to it',
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — goals, frustrations, or questions for our team?',
        type: 'textarea',
        placeholder: 'Nothing is too small or too ambitious.',
      },
    ],
  },
];
