import type { IntakeSection } from './types';

export const STOREFRONT_ENTERTAINMENT_SECTIONS: IntakeSection[] = [
  {
    id: 'business-overview',
    title: 'Your Business & Venue',
    description: "Let's start with who you are and what kind of experience you offer.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Jordan Price, Owner',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourvenue.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'businessName',
        label: 'Business or venue name',
        type: 'text',
        placeholder: 'e.g. Lazer Zone Family Fun Center',
      },
      {
        id: 'venueType',
        label: 'What best describes your venue?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'indoor-playground', label: 'Indoor playground / soft play' },
          { value: 'trampoline-park', label: 'Trampoline park' },
          { value: 'arcade', label: 'Arcade / game center' },
          { value: 'laser-tag', label: 'Laser tag' },
          { value: 'escape-room', label: 'Escape room' },
          { value: 'go-karts', label: 'Go-karts / ride attractions' },
          { value: 'mini-golf', label: 'Mini golf / putting' },
          { value: 'bowling', label: 'Bowling alley' },
          { value: 'climbing', label: 'Climbing / ninja course' },
          { value: 'vr-gaming', label: 'VR / immersive gaming' },
          { value: 'multi-attraction', label: 'Multi-attraction family entertainment center' },
        ],
      },
      {
        id: 'numberOfLocations',
        label: 'How many locations do you operate?',
        type: 'radio',
        options: [
          { value: 'one', label: '1 location' },
          { value: 'two-five', label: '2 – 5 locations' },
          { value: 'six-plus', label: '6+ locations' },
        ],
      },
    ],
  },
  {
    id: 'bookings-ticketing',
    title: 'Bookings, Ticketing & Reservations',
    description: "How customers book and pay is often the biggest friction point for entertainment venues.",
    fields: [
      {
        id: 'bookingSystem',
        label: 'How do customers currently book or buy tickets?',
        type: 'radio',
        options: [
          { value: 'online-self-serve', label: 'Online — fully self-serve booking / ticketing' },
          { value: 'online-form', label: 'Online form — staff confirms manually' },
          { value: 'phone-only', label: 'Phone or walk-in only' },
          { value: 'mix', label: 'Mix of online and phone' },
        ],
      },
      {
        id: 'bookingPlatform',
        label: 'What platform or tool are you using for bookings?',
        type: 'text',
        placeholder: 'e.g. Acuity, Bookeo, FareHarbor, Square, custom, none...',
        flag: 'pain',
      },
      {
        id: 'partyPackages',
        label: 'Do you offer birthday party or group event packages?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-online', label: 'Yes — bookable online' },
          { value: 'yes-manual', label: 'Yes — but only via phone or email request' },
          { value: 'no', label: 'No party packages currently' },
        ],
      },
      {
        id: 'waiversLiability',
        label: 'How do you collect liability waivers?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'digital-pre-arrival', label: 'Digital — signed online before arrival' },
          { value: 'digital-on-site', label: 'Digital — signed on a tablet at check-in' },
          { value: 'paper', label: 'Paper waivers at the door' },
          { value: 'none', label: 'No waivers currently' },
        ],
      },
      {
        id: 'capacityManagement',
        label: 'Can you control and display real-time capacity or session availability online?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — live availability shown online' },
          { value: 'partial', label: 'Partially — some sessions managed online' },
          { value: 'no', label: 'No — capacity is managed manually' },
        ],
      },
    ],
  },
  {
    id: 'digital-presence',
    title: 'Digital Presence & Marketing',
    description: "Parents and groups research before they visit. Let's see how you show up.",
    fields: [
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — modern, easy to book, gets compliments' },
          { value: 'adequate', label: 'Adequate — functional but not impressive' },
          { value: 'outdated', label: 'Outdated — needs a full rebuild' },
          { value: 'none', label: 'No website currently' },
        ],
      },
      {
        id: 'googleMaps',
        label: 'Is your Google Business Profile up to date with photos, hours, and reviews?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — actively managed' },
          { value: 'partial', label: 'Partially — some info missing or outdated' },
          { value: 'no', label: 'No — not actively managed' },
        ],
      },
      {
        id: 'socialMedia',
        label: 'Which social platforms are you active on?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'instagram', label: 'Instagram' },
          { value: 'facebook', label: 'Facebook' },
          { value: 'tiktok', label: 'TikTok' },
          { value: 'youtube', label: 'YouTube' },
          { value: 'none', label: 'Not active on social media' },
        ],
      },
      {
        id: 'emailMarketing',
        label: 'Do you have an email or SMS marketing program?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-both', label: 'Yes — email and SMS' },
          { value: 'yes-email', label: 'Yes — email only' },
          { value: 'no-want', label: 'No, but I want to start one' },
          { value: 'no', label: 'No marketing list currently' },
        ],
      },
    ],
  },
  {
    id: 'membership-loyalty',
    title: 'Memberships, Passes & Loyalty',
    description: "Recurring revenue from memberships and passes is a major growth lever for entertainment venues.",
    fields: [
      {
        id: 'membershipProgram',
        label: 'Do you offer memberships or season passes?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-active', label: 'Yes — active and growing' },
          { value: 'yes-underused', label: 'Yes — but underperforming' },
          { value: 'no-want', label: 'No, but interested in launching one' },
          { value: 'no', label: 'No plans for memberships' },
        ],
      },
      {
        id: 'loyaltyPoints',
        label: 'Do you have a loyalty or rewards program for repeat visitors?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — points, punch card, or digital rewards' },
          { value: 'no-want', label: 'No, but I want one' },
          { value: 'no', label: 'Not a priority right now' },
        ],
      },
      {
        id: 'giftCards',
        label: 'Do you sell gift cards — physical or digital?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-both', label: 'Yes — physical and digital' },
          { value: 'yes-digital', label: 'Yes — digital only' },
          { value: 'yes-physical', label: 'Yes — physical only' },
          { value: 'no', label: 'No gift cards currently' },
        ],
      },
    ],
  },
  {
    id: 'operations',
    title: 'Staffing & Operations',
    description: "Behind every great guest experience is a well-run operation.",
    fields: [
      {
        id: 'staffCount',
        label: 'Approximately how many staff members do you have?',
        type: 'radio',
        options: [
          { value: 'under-10', label: 'Under 10' },
          { value: '10-30', label: '10 – 30' },
          { value: '31-plus', label: '31+' },
        ],
      },
      {
        id: 'posSystem',
        label: 'What POS or point-of-sale system do you use on-site?',
        type: 'text',
        placeholder: 'e.g. Square, Clover, Lightspeed, custom, none...',
      },
      {
        id: 'biggestOperationalChallenge',
        label: 'What is your biggest operational pain point right now?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. party booking chaos, waiver backlogs, staff scheduling, no-shows, outdated website...',
      },
    ],
  },
  {
    id: 'timeline-budget',
    title: 'Timeline, Budget & Final Thoughts',
    description: 'Last section — help us understand your timeline and what success looks like.',
    fields: [
      {
        id: 'launchDate',
        label: 'Is there a deadline or seasonal push driving this project?',
        type: 'text',
        placeholder: 'e.g. before summer, before holiday season, ASAP...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will manage it ourselves' },
          { value: 'retainer', label: "Monthly support retainer" },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'competitorReference',
        label: 'Is there another venue or competitor whose digital experience you admire?',
        type: 'text',
        placeholder: 'Paste a URL or describe what you like about their setup',
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — goals, blockers, or questions for our team?',
        type: 'textarea',
        placeholder: 'Nothing is too small.',
      },
    ],
  },
];
