import type { IntakeSection } from './types';

export const WAREHOUSING_SECTIONS: IntakeSection[] = [
  {
    id: 'business-facility',
    title: 'Business & Facility',
    description: "Let's start with your operation, facilities, and the types of inventory you handle.",
    fields: [
      {
        id: 'nameAndRole',
        label: 'Your name and role',
        type: 'text',
        placeholder: 'e.g. Dana Brooks, Operations Director',
        required: true,
      },
      {
        id: 'email',
        label: 'Email address',
        type: 'email',
        placeholder: 'you@yourwarehouse.com',
        sub: 'We will email your personalized discovery dashboard to this address.',
        required: true,
      },
      {
        id: 'companyName',
        label: 'Company or facility name',
        type: 'text',
        placeholder: 'e.g. Summit Storage & Fulfillment',
      },
      {
        id: 'facilityType',
        label: 'What best describes your warehousing operation?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'public-warehouse', label: 'Public / multi-client warehouse' },
          { value: 'private-warehouse', label: 'Private / dedicated warehouse' },
          { value: 'fulfillment-3pl', label: '3PL fulfillment center' },
          { value: 'cold-storage', label: 'Cold storage / temperature-controlled' },
          { value: 'bonded', label: 'Bonded / customs warehouse' },
          { value: 'cross-dock', label: 'Cross-dock / transload facility' },
          { value: 'self-storage', label: 'Self-storage / mini-warehouse' },
        ],
      },
      {
        id: 'facilityCount',
        label: 'How many facilities do you operate?',
        type: 'radio',
        options: [
          { value: 'one', label: '1 facility' },
          { value: 'two-five', label: '2 – 5 facilities' },
          { value: 'six-plus', label: '6+ facilities' },
        ],
      },
      {
        id: 'squareFootage',
        label: 'Approximate total square footage under management',
        type: 'radio',
        options: [
          { value: 'under-25k', label: 'Under 25,000 sq ft' },
          { value: '25k-100k', label: '25,000 – 100,000 sq ft' },
          { value: '100k-500k', label: '100,000 – 500,000 sq ft' },
          { value: '500k-plus', label: '500,000+ sq ft' },
        ],
      },
    ],
  },
  {
    id: 'clients-services',
    title: 'Client Types & Services',
    description: 'Understanding who you serve and what services you offer shapes the right digital experience.',
    fields: [
      {
        id: 'clientTypes',
        label: 'Who are your primary clients?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'ecommerce', label: 'Ecommerce brands / DTC' },
          { value: 'manufacturers', label: 'Manufacturers / distributors' },
          { value: 'retailers', label: 'Retailers / wholesalers' },
          { value: 'food-beverage', label: 'Food & beverage companies' },
          { value: 'healthcare', label: 'Healthcare / pharma' },
          { value: 'government', label: 'Government / public sector' },
          { value: 'individuals', label: 'Individual consumers (self-storage)' },
        ],
      },
      {
        id: 'servicesOffered',
        label: 'Which services do you offer beyond basic storage?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'pick-pack', label: 'Pick, pack & ship' },
          { value: 'kitting', label: 'Kitting / assembly' },
          { value: 'returns', label: 'Returns processing' },
          { value: 'inventory-mgmt', label: 'Inventory management & reporting' },
          { value: 'freight', label: 'Freight coordination / LTL / FTL' },
          { value: 'labeling', label: 'Labeling / relabeling' },
          { value: 'storage-only', label: 'Storage only' },
        ],
      },
      {
        id: 'clientPortal',
        label: 'Do clients have a portal to view inventory, orders, or billing?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-robust', label: 'Yes — robust self-service portal' },
          { value: 'yes-basic', label: 'Yes — basic / limited functionality' },
          { value: 'no-want', label: 'No — and we want to add this' },
          { value: 'no', label: 'No client portal' },
        ],
      },
      {
        id: 'onboardingProcess',
        label: 'How do new clients currently get onboarded?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. phone call, site visit, manual paperwork, email back-and-forth...',
      },
    ],
  },
  {
    id: 'wms-technology',
    title: 'WMS & Technology',
    description: 'Your warehouse management stack is the backbone of operational visibility.',
    fields: [
      {
        id: 'wmsSystem',
        label: 'What WMS (Warehouse Management System) do you use?',
        type: 'radio',
        options: [
          { value: 'manhattan', label: 'Manhattan Associates' },
          { value: 'blue-yonder', label: 'Blue Yonder' },
          { value: 'oracle', label: 'Oracle WMS' },
          { value: 'fishbowl', label: 'Fishbowl' },
          { value: 'deposco', label: 'Deposco' },
          { value: 'custom', label: 'Custom-built system' },
          { value: 'spreadsheets', label: 'Spreadsheets / manual tracking' },
          { value: 'other', label: 'Other' },
        ],
      },
      {
        id: 'integrations',
        label: 'Which systems does your WMS need to integrate with?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'ecommerce-platforms', label: 'Ecommerce platforms (Shopify, Amazon, etc.)' },
          { value: 'erp', label: 'ERP (NetSuite, SAP, etc.)' },
          { value: 'tms', label: 'TMS / freight carriers' },
          { value: 'accounting', label: 'Accounting / billing (QuickBooks, etc.)' },
          { value: 'edi', label: 'EDI / B2B trading partners' },
          { value: 'barcode-rfid', label: 'Barcode / RFID scanning hardware' },
        ],
      },
      {
        id: 'realTimeVisibility',
        label: 'Can clients see real-time inventory levels and order status?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — fully automated and visible' },
          { value: 'partial', label: 'Partially — some manual updates required' },
          { value: 'no-want', label: 'No — and this is a priority' },
          { value: 'no', label: 'No real-time visibility' },
        ],
      },
      {
        id: 'techPain',
        label: 'What is your biggest technology or systems pain point?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. manual data entry between systems, no API access, outdated WMS, reporting is painful...',
      },
    ],
  },
  {
    id: 'digital-presence',
    title: 'Digital Presence & Lead Generation',
    description: 'How prospects find you and evaluate your capabilities before signing a contract.',
    fields: [
      {
        id: 'currentWebsite',
        label: 'How would you describe your current website?',
        type: 'radio',
        options: [
          { value: 'strong', label: 'Strong — professional, drives inquiries' },
          { value: 'adequate', label: 'Adequate — functional but not competitive' },
          { value: 'outdated', label: 'Outdated — needs a full rebuild' },
          { value: 'none', label: 'No website currently' },
        ],
      },
      {
        id: 'websitePain',
        label: 'What frustrates you most about your current online presence?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. no way to request a quote online, no facility photos, hard to explain our services...',
      },
      {
        id: 'leadSources',
        label: 'Where do most new client inquiries come from?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'referrals', label: 'Referrals from existing clients' },
          { value: 'google', label: 'Google search / local SEO' },
          { value: 'broker-networks', label: 'Broker networks / load boards' },
          { value: 'trade-shows', label: 'Trade shows / industry events' },
          { value: 'cold-outreach', label: 'Cold outreach / sales team' },
          { value: 'rfp', label: 'RFP / bid responses' },
        ],
      },
      {
        id: 'quoteRequest',
        label: 'Can prospects request a quote or facility tour online?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes-automated', label: 'Yes — automated online quote or inquiry form' },
          { value: 'yes-manual', label: 'Yes — form exists but requires manual follow-up' },
          { value: 'no-want', label: 'No — and we want to add this' },
          { value: 'no', label: 'No online inquiry process' },
        ],
      },
    ],
  },
  {
    id: 'pricing-contracts',
    title: 'Pricing & Contracts',
    description: 'How you price and contract services affects both sales velocity and client retention.',
    fields: [
      {
        id: 'pricingModel',
        label: 'How do you primarily price your services?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'per-pallet', label: 'Per pallet / per unit stored' },
          { value: 'per-sqft', label: 'Per square foot' },
          { value: 'per-order', label: 'Per order / pick fee' },
          { value: 'monthly-minimum', label: 'Monthly minimum commitment' },
          { value: 'custom-quote', label: 'Fully custom quote per client' },
        ],
      },
      {
        id: 'contractLength',
        label: 'What is your typical contract term?',
        type: 'radio',
        options: [
          { value: 'month-to-month', label: 'Month-to-month' },
          { value: 'annual', label: 'Annual contract' },
          { value: 'multi-year', label: 'Multi-year (2+ years)' },
          { value: 'varies', label: 'Varies by client' },
        ],
      },
      {
        id: 'pricingTransparency',
        label: 'Is your pricing visible to prospects before they contact you?',
        type: 'radio',
        flag: 'upsell',
        options: [
          { value: 'yes', label: 'Yes — pricing or rate cards are published' },
          { value: 'partial', label: 'Partial — some pricing guidance available' },
          { value: 'no-want', label: 'No — but we want to be more transparent' },
          { value: 'no', label: 'No — all pricing is custom / quote-based' },
        ],
      },
      {
        id: 'billingPain',
        label: 'What is the biggest friction in your billing or invoicing process?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. manual invoice generation, disputes over storage charges, no client-facing billing portal...',
      },
    ],
  },
  {
    id: 'operations-staffing',
    title: 'Operations & Staffing',
    description: 'Day-to-day execution challenges that technology and process improvements can address.',
    fields: [
      {
        id: 'staffCount',
        label: 'Approximately how many warehouse staff do you employ?',
        type: 'radio',
        options: [
          { value: 'under-10', label: 'Under 10' },
          { value: '10-50', label: '10 – 50' },
          { value: '51-200', label: '51 – 200' },
          { value: '200-plus', label: '200+' },
        ],
      },
      {
        id: 'shiftModel',
        label: 'What shift model do you operate?',
        type: 'radio',
        options: [
          { value: 'single', label: 'Single shift (daytime only)' },
          { value: 'two-shift', label: 'Two shifts' },
          { value: '24-7', label: '24/7 operations' },
        ],
      },
      {
        id: 'biggestOpsPain',
        label: 'What is your single biggest operational challenge today?',
        type: 'textarea',
        flag: 'pain',
        placeholder: 'e.g. labor shortages, inaccurate inventory counts, slow receiving, client communication gaps...',
      },
      {
        id: 'safetyCompliance',
        label: 'Are there compliance or certification requirements you need to highlight?',
        type: 'checkbox',
        sub: 'Check all that apply.',
        options: [
          { value: 'fda', label: 'FDA / food safety (SQF, BRC, etc.)' },
          { value: 'iso', label: 'ISO certification' },
          { value: 'osha', label: 'OSHA compliance' },
          { value: 'hazmat', label: 'Hazmat / dangerous goods' },
          { value: 'customs-bonded', label: 'Customs bonded / FTZ' },
          { value: 'none', label: 'No special certifications' },
        ],
      },
    ],
  },
  {
    id: 'timeline-budget',
    title: 'Timeline, Budget & Final Thoughts',
    description: "Last section — let's align on priorities and investment level.",
    fields: [
      {
        id: 'primaryGoal',
        label: 'What is your primary goal for this engagement?',
        type: 'radio',
        options: [
          { value: 'new-website', label: 'Build or rebuild a professional website' },
          { value: 'client-portal', label: 'Add or improve a client self-service portal' },
          { value: 'more-leads', label: 'Generate more qualified client inquiries' },
          { value: 'streamline-onboarding', label: 'Streamline client onboarding and quoting' },
          { value: 'integrations', label: 'Improve system integrations and visibility' },
          { value: 'multiple', label: "Multiple goals — let's discuss" },
        ],
      },
      {
        id: 'launchDate',
        label: 'Is there a deadline or busy season driving this project?',
        type: 'text',
        placeholder: 'e.g. before peak season, before a new facility opens, ASAP...',
      },
      {
        id: 'budget',
        label: 'What is your approximate budget for this engagement?',
        type: 'radio',
        options: [
          { value: 'under-2k', label: 'Under $2,000' },
          { value: '2k-5k', label: '$2,000 – $5,000' },
          { value: '5k-15k', label: '$5,000 – $15,000' },
          { value: '15k-plus', label: '$15,000+' },
          { value: 'flexible', label: 'Flexible — depends on scope' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'maintenance',
        label: 'After launch, how would you like to handle ongoing support?',
        type: 'radio',
        options: [
          { value: 'self-manage', label: 'We will handle it ourselves' },
          { value: 'retainer', label: 'Monthly support retainer' },
          { value: 'on-call', label: 'On-call help as needed' },
          { value: 'not-sure', label: 'Not sure yet' },
        ],
      },
      {
        id: 'brandIdentity',
        label: 'Do you have an established brand identity (logo, colors, fonts)?',
        type: 'radio',
        options: [
          { value: 'established', label: "Yes — brand is solid, don't change it" },
          { value: 'refresh', label: 'Yes — but open to a refresh' },
          { value: 'need-help', label: 'No — we need full branding help' },
        ],
      },
      {
        id: 'additionalNotes',
        label: 'Anything else — goals, frustrations, or questions for our team?',
        type: 'textarea',
        placeholder: 'No detail is too small.',
      },
    ],
  },
];
